www.altria.com/-/media/Project/Altria/Altria/responsibility/corporate-responsibility-reports/reducing-harm-and-preventing-underage-use-2020-2021.pdf
soprweb.senate.gov/index.cfm?event=getFilingDetails&filingID=01BC6236-C956-4519-B801-5F505B4A07DE&filingTypeID=78
www.conference-board.org/politicalspending/
disclosurespreview.house.gov/ld/ldxmlrelease/2021/Q3/301314989.xml
www.altria.com/about-altria/board-of-directors-and-corporate-governance/board-of-directors-at-a-glance/w-leo-kiely-iii
www.altria.com/responsibility/drive-responsibility-through-our-value-chain/responsible-sourcing-in-our-operations
www.altria.com/moving-beyond-smoking/reduce-the-harm-of-tobacco-products
www.altria.com/responsibility/drive-responsibility-through-our-value-chain/engaging-trade-partners-in-responsibility
www.fda.gov/news-events/speeches-fda-officials/protecting-american-families-comprehensive-approach-nicotine-and-tobacco-06282017
www.altria.com/people-and-careers/student-internships
careers.altria.com/
www.altria.com/-/media/Project/Altria/Altria/about-altria/board-of-directors-and-corporate-governance/board-committees/charters/Compensation-Committee-Charter.pdf
www.altria.com/about-altria/at-a-glance
www.altria.com/moving-beyond-smoking/our-approach-to-harm-reduction
disclosurespreview.house.gov/ld/ldxmlrelease/2021/Q4/301338657.xml
soprweb.senate.gov/index.cfm?event=getFilingDetails&filingID=645CFB12-31A8-48BB-BF85-4CC1CF1589B4&filingTypeID=60
johnmiddletonco.com
www.altria.com/-/media/Project/Altria/Altria/about-altria/board-of-directors-and-corporate-governance/board-committees/charters/Executive-Committee-Charter.pdf
www.altria.com/about-altria/our-voice-and-actions/the-evolution-of-our-underage-prevention-grant-portfolio
www.altria.com/-/media/Project/Altria/Altria/responsibility/corporate-responsibility-reports/reducing-harm-and-preventing-underage-use-2020-2021.pdf?src=preventing-underage-use
www.altria.com/about-altria/federal-regulation-of-tobacco/tobacco-product-application-pathways
www.altria.com/about-altria/federal-regulation-of-tobacco/menthol-in-cigarettes-and-cigar-flavors
www.altria.com/about-altria/government-affairs/public-policy-positions/tax-policy-should-give-less-harmful-products-a-better-chance
www.altria.com/-/media/Project/Altria/Altria/about-altria/board-of-directors-and-corporate-governance/board-committees/charters/Finance-Committee-Charter.pdf
www.altria.com/people-and-careers/our-people-and-communities/well-being-of-employees-and-communities
www.altria.com/about-altria/board-of-directors-and-corporate-governance/board-of-directors-at-a-glance/ellen-strahlman
investor.altria.com/stock-performance/tools-calculators/default.aspx
www.altria.com/moving-beyond-smoking/communicating-tobacco-health-effects
www.altria.com/people-and-careers/hiring-process
www.altria.com/-/media/Project/Altria/Altria/harm-reduction/helping-reduce-underage-tobacco-use/standards-for-underage-use-prevention.pdf
www.altria.com/about-altria/our-leadership/scott-myers
www.altria.com/Overlays/Companies-and-Brands/JUUL
www.instagram.com/4consumerchoice/
www.altria.com/responsibility/drive-responsibility-through-our-value-chain/human-rights-ethics-and-compliance
sciencebasedtargets.org/
investor.altria.com/press-releases/news-details/2022/Altria-Group-Inc.-Director-Dinyar-S.-Devitre-Announces-Decision-to-Retire-From-Board-of-Directors/default.aspx 
www.altria.com/about-altria/our-leadership/paige-magness
www.altria.com/responsibility/drive-responsibility-through-our-value-chain/grower-support-and-agricultural-sustainability/green-tobacco-sickness
www.altria.com/people-and-careers/our-people-and-communities
www.altria.com/about-altria/board-of-directors-and-corporate-governance/board-of-directors-at-a-glance/kathryn-b-mcquade
lda.senate.gov/filings/public/filing/edbc2ecf-b279-4f20-a96c-b8f2707fa201/print/
www.altria.com/Overlays/Companies-and-Brands/JMC
investor.altria.com/at-a-glance/default.aspx
www.altria.com/-/media/Project/Altria/Altria/about-altria/board-of-directors-and-corporate-governance/about_altria_BOD_codeethics.pdf
soprweb.senate.gov/index.cfm?event=getFilingDetails&filingID=D95D7E56-F520-44FA-8E8A-7A13DFD0DE7A&filingTypeID=78
www.altria.com/about-altria/board-of-directors-and-corporate-governance/board-of-directors-at-a-glance/john-t-casteen-iii
www.altria.com/Overlays/Companies-and-Brands/Helix
www.quitassist.com/
www.altria.com/-/media/Project/Altria/Altria/about-altria/board-of-directors-and-corporate-governance/board-committees/charters/Audit-Committee-Charter.pdf
www.altria.com/about-altria/our-leadership/sal-mancuso
disclosurespreview.house.gov/ld/ldxmlrelease/2020/Q1/301178932.xml
www.altria.com/about-altria/government-affairs/disclosures-and-transparency
soprweb.senate.gov/index.cfm?event=getFilingDetails&filingID=40FB6564-4752-4440-A674-558FA8D897C1&filingTypeID=60
www.altria.com/-/media/Project/Altria/Altria/responsibility/corporate-responsibility-reports/reducing-harm-and-preventing-underage-use-2020-2021.pdf?src=moving-beyond-smoking
soprweb.senate.gov/index.cfm?event=getFilingDetails&filingID=FAD0CE2F-9A72-4D1A-814A-50DF9C1D8481&filingTypeID=78
www.twitter.com/altrianews
www.altria.com/about-altria/our-voice-and-actions/the-critical-importance-of-engagement-with-the-public-health-and-scientific-communities
www.altria.com/-/media/Project/Altria/Altria/responsibility/environmental-management/CDP-forests-Response.pdf
www.altria.com/about-altria/our-heritage
www.altria.com/about-altria/government-affairs/compliance-and-oversight/directors
www.pointsoflight.org/
www.altria.com/responsibility/prevent-underage-use/responsible-marketing
www.altria.com/people-and-careers/benefits/providing-work-life-balance
www.altria.com/about-altria/our-voice-and-actions/our-focus-on-responsibility-before-and-after-fda-authorization
www.altria.com/ca-privacy
www.altria.com/responsibility/drive-responsibility-through-our-value-chain/responsible-sourcing-in-our-operations/child-and-forced-labor
www.caron.org/
www.altria.com/responsibility/at-a-glance/2025-responsibility-focus-areas-and-goals
www.altria.com/-/media/Project/Altria/Altria/about-altria/board-of-directors-and-corporate-governance/board-committees/charters/Nominating-Committee-Charter.pdf
www.altria.com/Overlays/Companies-and-Brands/PMCC
www.altria.com/about-altria/board-of-directors-and-corporate-governance/board-of-directors-at-a-glance/debra-j-kelly-ennis
www.altria.com/about-altria/government-affairs/public-policy-positions/racial-and-economic-equity-policy-activities
www.altria.com/responsibility/protect-the-environment?src=2025-focus-areas-goals
www.altria.com/responsibility/drive-responsibility-through-our-value-chain
www.altria.com/about-altria/our-leadership/jody-begley
www.senate.gov/pagelayout/legislative/g_three_sections_with_teasers/lobbyingdisc.htm
www.altria.com/about-altria/our-voice-and-actions/recognizing-our-business-partners
www.altria.com/people-and-careers/military-and-veterans
www.altria.com/moving-beyond-smoking?src=federal-regulation-of-tobacco
www.altria.com/about-altria/our-voice-and-actions/environmental-sustainability-in-the-smoke-free-product-development-pipeline
lobbyingdisclosure.house.gov/
www.altria.com/responsibility/drive-responsibility-through-our-value-chain/supporting-supplier-diversity-and-inclusion
www.altria.com/responsibility/drive-responsibility-through-our-value-chain/human-rights-ethics-and-compliance/conflict-minerals
www.altria.com/-/media/Project/Altria/Altria/responsibility/at-a-glance/focus-areas-and-goals/2020-2021-cr-engage-and-lead-responsibly-report.pdf?src=board-of-directors
www.altria.com/about-altria/our-leadership/shannon-leistra
www.altria.com/responsibility/protect-the-environment/environmental-management-framework
www.altria.com/submit-your-idea?src=reducing-the-harm-of-tobacco-products
disclosurespreview.house.gov/ld/ldxmlrelease/2020/4A/301249381.xml
investor.altria.com/events-presentations/default.aspx
investor.altria.com/stock-performance/industry-analysts/default.aspx
disclosurespreview.house.gov/ld/ldxmlrelease/2021/Q1/301266961.xml
www.johnmiddletonco.com/
www.altria.com/moving-beyond-smoking/science-research-and-development/animal-care-and-use-statement
www.altria.com/-/media/Project/Altria/Altria/responsibility/corporate-responsibility-reports/protect-the-environment-2020-2021.pdf?src=natural-resources-conservation
www.altria.com/about-altria/our-voice-and-actions/investing-in-higher-education-and-agricultural-studies
www.altria.com/about-altria/our-leadership/megan-witherspoon
www.altria.com/-/media/Project/Altria/Altria/responsibility/corporate-responsibility-reports/reducing-harm-and-preventing-underage-use-2020-2021.pdf?src=prevent-underage-use
investor.altria.com/press-releases/news-details/2020/Altria-Announces-Five-Million-Dollar-Donation-to-Fight-Racial-Inequality/default.aspx
www.altria.com/about-altria/board-of-directors-and-corporate-governance/contact-the-board
www.altria.com/-/media/Project/Altria/Altria/about-altria/board-of-directors-and-corporate-governance/board-committees/charters/Innovation-Committee-Charter.pdf
www.altria.com/Overlays/Companies-and-Brands/USSTC
soprweb.senate.gov/index.cfm?event=getFilingDetails&filingID=43B4D867-794C-455F-8017-C2EB872FA49E&filingTypeID=51
www.altria.com/-/media/Project/Altria/Altria/responsibility/environmental-management/climate-change/GHG-Emissions-Footprint.pdf
www.altria.com/about-altria/who-we-are/corporate-profile
www.altria.com/responsibility/drive-responsibility-through-our-value-chain/human-rights-ethics-and-compliance/human-rights-framework
www.altria.com/about-altria/our-heritage?tab=inclusion__diversity--equityheritage
soprweb.senate.gov/index.cfm?event=getFilingDetails&filingID=934E404A-FB84-47DF-9A6D-22A1F7FB46C9&filingTypeID=78
www.fda.gov/tobacco-products/health-information/nicotine-addictive-chemical-tobacco-products
twitter.com/4tobaccorights
investor.altria.com/sec-filings/default.aspx
www.altria.com/about-altria/our-companies
www.altria.com/responsibility/drive-responsibility-through-our-value-chain/human-rights-ethics-and-compliance/california-transparency-in-supply-chains-act
www.osha.gov/
www.altria.com/-/media/Project/Altria/Altria/responsibility/corporate-responsibility-reports/reducing-harm-and-preventing-underage-use-2020-2021.pdf?src=our-product-platforms
www.altria.com/submit-your-idea
www.altria.com/about-altria/our-leadership/todd-walker
sciences.altria.com/
www.altria.com/about-altria/federal-regulation-of-tobacco
www.altria.com/Overlays/Companies-and-Brands/PMUSA
www.altria.com/people-and-careers/benefits/supporting-you-and-your-loved-ones
www.linkedin.com/company/altria
www.fda.gov/tobacco-products
www.altria.com/about-altria/our-cultural-aspiration
www.altria.com/moving-beyond-smoking
www.altria.com/-/media/Project/Altria/Altria/about-altria/our-heritage/BHM-infographic.pdf
investor.altria.com/financial-info/return-of-capital/default.aspx
www.altria.com/about-altria/government-affairs/public-policy-positions/corporate-tax
www.altria.com/people-and-careers/benefits/investing-in-your-future
soprweb.senate.gov/index.cfm?event=getFilingDetails&filingID=B1C53F68-1934-4988-8E32-E69A29472D7C&filingTypeID=78
www.altria.com/about-altria/our-voice-and-actions/advancing-the-science---making-a-difference
soprweb.senate.gov/index.cfm?event=getFilingDetails&filingID=58440EA2-ACE7-45DB-B2EB-8873AC267CA3&filingTypeID=69
www.altria.com/about-altria/our-leadership/dominik-meier
investor.altria.com/frequently-asked-questions/default.aspx
www.altria.com/people-and-careers/benefits
kab.org/programs/cigarette-litter/
www.altria.com/about-altria/our-voice-and-actions/partnering-on-responsible-labor-practices-with-international-leaf-suppliers
www.altria.com/about-altria/our-companies/philip-morris-capital-corporation
www.altria.com/about-altria/federal-regulation-of-tobacco/regulation-of-flavors-in-tobacco-products
www.altria.com/responsibility/protect-the-environment/natural-resource-conservation
www.altria.com/-/media/Project/Altria/Altria/responsibility/corporate-responsibility-reports/tcfd-report.pdf
www.altria.com/about-altria/awards-and-recognition
www.altria.com/people-and-careers/our-people-and-communities/inclusion-and-diversity/employee-resource-groups
investor.altria.com/financial-info/default.aspx
www.altria.com/about-altria/our-voice-and-actions/adopting-age-validation-technology-at-retail
www.altria.com/about-altria/our-vision
www.altria.com/about-altria/government-affairs
www.ilo.org/declaration/lang--en/index.htm
www.altria.com/about-altria/government-affairs/public-policy-positions/fdas-role-as-regulator-of-ingredients-and-flavors
www.altria.com/moving-beyond-smoking/public-policy-positions
www.altria.com/about-altria/government-affairs/federal-lobbying-disclosures
www.altria.com/people-and-careers/our-people-and-communities/workforce-and-community-capability-building
www.quitassist.com
investor.altria.com/annual-report-proxy-statement-annual-meeting/default.aspx
www.altria.com/-/media/Project/Altria/Altria/responsibility/environmental-management/CDP-Water-Response.pdf
www.altria.com/people-and-careers/our-people-and-communities/community-impact-and-partnership
www.altria.com/submit-your-idea?src=our-product-platforms
www.altria.com/about-altria/our-leadership/hernan-tabah
www.altria.com/responsibility/prevent-underage-use/positive-youth-development
investor.altria.com/corporate-profile/default.aspx?src=megaspotlight
lda.senate.gov/filings/public/filing/9043df67-71e2-4840-96c5-8b4561583e48/print/
www.altria.com/people-and-careers/our-people-and-communities/inclusion-and-diversity
www.philipmorrisusa.com/products/tobacco-settlement-agreements
www.altria.com/responsibility/drive-responsibility-through-our-value-chain/grower-support-and-agricultural-sustainability
www.altria.com/responsibility/drive-responsibility-through-our-value-chain?src=2025-focus-areas-goals
www.altria.com/responsibility/protect-the-environment/environmental-impact-of-products
investor.altria.com/stock-ownership/default.aspx
www.altria.com/about-altria/our-voice-and-actions/collaborating-for-retail-access-prevention-solutions
www.altria.com/people-and-careers
www.altria.com/about-altria/our-leadership/michael-thorne-begland
www.ussmokeless.com
www.altria.com/-/media/Project/Altria/Altria/about-altria/board-of-directors-and-corporate-governance/notice-of-annual-meeting-of-shareholders-and-proxy-statement.pdf
www.altria.com/-/media/Project/Altria/Altria/responsibility/supply-chain-responsibility/communicating-our-expectations/tobacco-gap-program-supplemental-guidelines.pdf
www.fda.gov/tobacco-products/health-effects-tobacco-use/nicotine-why-tobacco-products-are-addictive
www.altria.com/about-altria/our-voice-and-actions/driving-a-strategy-to-support-adult-consumers-in-cessation
www.altria.com/moving-beyond-smoking?src=supporting-cessation
www.ohchr.org/Documents/Publications/GuidingPrinciplesBusinessHR_EN.pdf
www.altria.com/about-altria/board-of-directors-and-corporate-governance/board-committees
www.altria.com/about-altria/government-affairs/public-policy-positions/protecting-the-legal-regulated-market-from-illegal-trade
www.ussmokeless.com/
www.altria.com/about-altria/board-of-directors-and-corporate-governance/board-of-directors-at-a-glance/virginia-e-shanks
soprweb.senate.gov/index.cfm?event=getFilingDetails&filingID=BCEF504F-79A2-4369-8981-5E78B99F7B96&filingTypeID=69
www.altria.com/-/media/Project/Altria/Altria/responsibility/corporate-responsibility-reports/drive-responsibility-through-our-value-chain-2020-2021.pdf?src=grower-support-and-agricultural-sustainability
www.altria.com/about-altria/who-we-are
disclosurespreview.house.gov/ld/ldxmlrelease/2020/Q3/301224117.xml
www.altria.com/-/media/Project/Altria/Altria/responsibility/supply-chain-responsibility/supplier-code-of-conduct.pdf
www.altria.com/about-altria/our-voice-and-actions/iqos-and-the-itc-decision
thecronosgroup.com/
www.altria.com/responsibility/protect-the-environment/climate-change
www.altria.com/moving-beyond-smoking/at-a-glance
www.cdp.net/en/scores
disclosurespreview.house.gov/ld/ldxmlrelease/2021/Q2/301290968.xml
investor.altria.com/press-releases/news-details/2020/Altria-Recognized-for-Environmental-Leadership/default.aspx
www.altria.com/about-altria/board-of-directors-and-corporate-governance/board-of-directors-at-a-glance/nabil-y-sakkab
www.altria.com/responsibility/prevent-underage-use/foundational-research
www.altria.com/-/media/Project/Altria/Altria/responsibility/corporate-responsibility-reports/drive-responsibility-through-our-value-chain-2020-2021.pdf?src=sourcing-in-our-operations
soprweb.senate.gov/index.cfm?event=getFilingDetails&filingID=07671656-27EC-4F11-B4B7-C8F9CD8BF9C6&filingTypeID=69
www.altria.com/submit-your-idea?src=science-research-development
www.altria.com/moving-beyond-smoking/our-product-platforms
www.altria.com/-/media/Project/Altria/Altria/responsibility/driving-responsibility-through-our-value-chain/grower-support-and-agricultural-sustainability/Tobacco-Leaders-Program-from-Ag-Practices.pdf
soprweb.senate.gov/index.cfm?event=getFilingDetails&filingID=2862443F-EB24-4C26-BCD9-504B9FEABCB6&filingTypeID=60
investor.altria.com/press-releases/default.aspx
www.altria.com/about-altria/government-affairs/public-policy-positions/supporting-science-based-fda-regulation
www.altria.com/about-altria/government-affairs/public-policy-positions/legislation-preventing-underage-use
www.facebook.com/4ConsumerChoice/
www.gapconnections.com/uploads/2020%20GAPC%20Certification%20Compliance%20Guide_Final_12132019.pdf
www.altria.com/about-altria/our-leadership/jay-zapko
www.altria.com/about-altria/our-leadership/jennifer-hunter
www.altria.com/-/media/Project/Altria/Altria/responsibility/corporate-responsibility-reports/protect-the-environment-2020-2021.pdf?src=natural-resource-conservation
lda.senate.gov/filings/public/filing/8ada2c4e-5811-481e-8976-6cc3ed3f3ca8/print/
www.altria.com/-/media/Project/Altria/Altria/responsibility/corporate-responsibility-reports/protect-the-environment-2020-2021.pdf?src=home
investor.altria.com/press-releases/news-details/2022/Altria-Named-Leader-in-Sustainable-Supply-Chain-Management/default.aspx
investor.altria.com/stock-performance/dividend-information/default.aspx
investor.altria.com/at-a-glance/default.aspx?src=homepage
www.altria.com/about-altria/board-of-directors-and-corporate-governance/board-of-directors-at-a-glance/r-matt-davis
www.altria.com/about-altria/our-voice-and-actions/engaging-with-policy-makers-on-the-science-of-potentially-reduced-harm-tobacco-products
www.altria.com/about-altria/board-of-directors-and-corporate-governance/board-of-directors-at-a-glance/marjorie-m-connelly
www.gapconnections.com/
www.altria.com/moving-beyond-smoking?src=responsibility-at-a-glance
www.altria.com/about-altria/our-leadership/maria-gogova
www.altria.com/responsibility
www.altria.com/about-altria/our-leadership
www.altria.com/-/media/Project/Altria/Altria/about-altria/board-of-directors-and-corporate-governance/about_altria_governance_RestatedArticles.pdf
www.altria.com/about-altria/our-voice-and-actions/capitalizing-on-simplification-and-sustainability-in-sales
www.altria.com/about-altria/government-affairs/state-lobbying-disclosures
www.altria.com/about-altria/our-voice-and-actions/partnership-for-innovative-water-reuse
www.altria.com/responsibility/at-a-glance
www.altria.com/about-altria/government-affairs/public-policy-positions
www.altria.com/about-altria/board-of-directors-and-corporate-governance/board-of-directors-at-a-glance/dinyar-s-devitre
tobaccorights.com/
www.altria.com/-/media/Project/Altria/Altria/responsibility/environmental-management/CDP-Climate-Change-Response.pdf
www.philipmorrisusa.com/
www.altria.com/moving-beyond-smoking?src=home-page-video
www.altria.com/-/media/Project/Altria/Altria/about-altria/board-of-directors-and-corporate-governance/Related-Person-Transactions-Policy.pdf
www.altria.com/responsibility/prevent-underage-use?src=2025-focus-areas-goals
www.altria.com/-/media/Project/Altria/Altria/responsibility/at-a-glance/focus-areas-and-goals/2020-2021-cr-engage-and-lead-responsibly-report.pdf?src=2025-responsibility-focus-areas-and-goals
tobaccoissues.com
soprweb.senate.gov/index.cfm?event=getFilingDetails&filingID=B637D8D5-CB0B-444A-A431-731BE1D35D3B&filingTypeID=69
www.altria.com/-/media/Project/Altria/Altria/responsibility/corporate-responsibility-reports/reducing-harm-and-preventing-underage-use-2020-2021.pdf?src=responsible-marketing
www.altria.com/about-altria/our-voice-and-actions/championing-environmental-impact-through-our-value-chains
investor.altria.com/press-releases/news-details/2021/Altria-Group-Joins-The-Valuable-500-in-Support-of-Individuals-with-Disabilities/default.aspx
www.altria.com/-/media/Project/Altria/Altria/responsibility/2019-cr-report.pdf
www.altria.com/-/media/Project/Altria/Altria/responsibility/corporate-responsibility-reports/drive-responsibility-through-our-value-chain-2020-2021.pdf?src=our-value-chain
www.altria.com/about-altria/government-affairs/engaging-with-others
investor.altria.com/press-releases/email-alerts-and-rss-newsfeeds/default.aspx
www.altria.com/-/media/Project/Altria/Altria/about-altria/board-of-directors-and-corporate-governance/Altria_RestatedArticlesofIncorporation.pdf
www.altria.com/about-altria/our-voice-and-actions
www.johnmiddletonco.com
www.altria.com/about-altria/our-voice-and-actions/new-opportunities-to-responsibly-engage-stakeholders-on-environmental-policy
www.altria.com/-/media/Project/Altria/Altria/about-altria/our-stories/The-Path-Forward-on-Harm-Reduction/the-path-forward-on-harm-reduction-speech.pdf
www.altria.com/about-altria/our-voice-and-actions/promoting-supplier-diversity-and-inclusion-in-our-communities
www.altria.com/about-altria/our-voice-and-actions/ceo-action-for-racial-equity-fellowship
www.altria.com/-/media/Project/Altria/Altria/responsibility/at-a-glance/focus-areas-and-goals/2020-2021-cr-engage-and-lead-responsibly-report.pdf?src=protect-the-environment
investor.altria.com/financial-info/fixed-income-information/default.aspx
www.altria.com/about-altria/our-leadership/billy-gifford
twitter.com/4ConsumerChoice
www.altria.com/people-and-careers/our-people-and-communities?src=2025-focus-areas-goals
www.altria.com/about-altria/our-voice-and-actions/protecting-natural-habitats-through-responsible-agricultural-practices
www.altria.com/-/media/Project/Altria/Altria/about-altria/board-of-directors-and-corporate-governance/altria-corporate-governance-guidelines.pdf
www.hrw.org/
www.altria.com/about-altria/our-leadership/brandt-surgner
www.altria.com/moving-beyond-smoking/supporting-cessation
soprweb.senate.gov/index.cfm?event=getFilingDetails&filingID=754AE19B-DB0F-4711-9D3D-8B575DE25302&filingTypeID=51
www.altria.com/
soprweb.senate.gov/index.cfm?event=getFilingDetails&filingID=763FB8D5-7337-43B2-B696-9E7894F8DBF6&filingTypeID=51
www.altria.com/about-altria/our-leadership/heather-newman
www.altria.com/contact-us
thegbi.org/green-globes-certification/
www.altria.com/people-and-careers/our-people-and-communities/racial-and-economic-equity
www.theenterprisecenter.com/
soprweb.senate.gov/index.cfm?event=getFilingDetails&filingID=050E767C-25B1-4AEF-9088-763EA8A71E07&filingTypeID=51
www.instagram.com/4tobaccorights/
www.samhsa.gov/sites/default/files/synar_program_rvr_table_1997-2018_dec_11_2018.pdf
www.altria.com/-/media/Project/Altria/Altria/responsibility/corporate-responsibility-reports/reducing-harm-and-preventing-underage-use-2020-2021.pdf?src=reducing-the-harm-of-tobacco-products
investor.altria.com/stock-performance/default.aspx
soprweb.senate.gov/index.cfm?event=getFilingDetails&filingID=C704463D-6C5F-4404-A8D3-289E4C90104E&filingTypeID=60
soprweb.senate.gov/index.cfm?event=getFilingDetails&filingID=3DA69786-5BA8-49AE-B045-6643B078AD55&filingTypeID=51
www.altria.com/moving-beyond-smoking/science-research-and-development
www.altria.com/responsibility/protect-the-environment
www.altria.com/about-altria/government-affairs/public-policy-positions/adult-smokers-21plus-should-have-access-to-better-choices
www.altria.com/media
www.samhsa.gov/synar
www.altria.com/responsibility/environmental-management
www.altria.com/-/media/Project/Altria/Altria/people-and-careers/people-and-culture/altria_code_of_conduct.pdf
www.gapconnections.com/services/certification-program
www.altria.com/about-altria/our-leadership/mac-livingston
www.blueprintsprograms.org/
www.altria.com/about-altria/board-of-directors-and-corporate-governance/board-of-directors-at-a-glance
www.wsj.com/articles/explore-the-management-top-250-1512495698
www.facebook.com/CitizensforTobaccoRights
www.altria.com/about-altria/our-leadership/bob-mccarter
www.altria.com/-/media/Project/Altria/Altria/responsibility/corporate-responsibility-reports/protect-the-environment-2020-2021.pdf?src=environmental-impact-of-products
www.altria.com/about-altria/government-affairs/public-policy-positions/inclusion-and-diversity-policy-activities
www.facebook.com/Altria-Group-147856125304229
www.altria.com/about-altria/our-voice-and-actions/driving-collaboration-for-grower-sustainability
www.altria.com/-/media/Project/Altria/Altria/people-and-careers/people-and-culture/code-of-conduct-principles.pdf
www.altria.com/about-altria/board-of-directors-and-corporate-governance
www.altria.com/moving-beyond-smoking?src=science-research-development
www.altria.com/responsibility/corporate-responsibility-reports
www.altria.com/responsibility/prevent-underage-use/foundational-research?src=preventing-underage-use
www.altria.com/-/media/Project/Altria/Altria/about-altria/board-of-directors-and-corporate-governance/ALTRIA_GROUP_BY_LAWS.pdf
www.unglobalcompact.org/AboutTheGC/TheTenPrinciples/humanRights.html
lda.senate.gov/filings/public/filing/61970c59-b96c-4309-8b97-aead3087004d/print/
www.altria.com/about-altria/our-voice-and-actions/supporting-our-trade-partners-through-responsible-programs
www.altria.com/moving-beyond-smoking?src=our-10-year-vision-image
www.ab-inbev.com/
www.altria.com/about-altria/our-voice-and-actions/our-science-based-approach-to-new-tobacco-products
www.altria.com/about-altria/our-leadership/kenya-blake
www.altria.com/about-altria/our-voice-and-actions/inclusive-communities-and-culture
www.altria.com/Overlays/Companies-and-Brands/ABInBev
monitoringthefuture.org/data/21data/table7.pdf
www.altria.com/moving-beyond-smoking?src=our-product-platforms
www.altria.com/about-altria/federal-regulation-of-tobacco/regulatory-filings
www.altria.com/about-altria/our-leadership/murray-garnick
www.altria.com/about-altria/board-of-directors-and-corporate-governance?src=2025-focus-areas-goals
www.altria.com/about-altria/federal-regulation-of-tobacco/nicotine-product-standard-in-cigarettes
www.philipmorrisusa.com
www.fda.gov/tobacco-products/rules-regulations-and-guidance/family-smoking-prevention-and-tobacco-control-act-overview
www.altria.com/about-altria/government-affairs/compliance-and-oversight
www.altria.com/about-altria/government-affairs/public-policy-positions/cannabis-and-cbd
www.nfwf.org/Pages/default.aspx
www.youtube.com/user/Altria
investor.altria.com/press-releases/news-details/2022/Altria-to-Host-Webcast-as-Part-of-the-Consumer-Analyst-Group-of-New-York-Conference/default.aspx 
www.altria.com/privacy
www.altria.com/moving-beyond-smoking?src=our-10-year-vision-text
www.altria.com/-/media/Project/Altria/Altria/responsibility/corporate-responsibility-reports/protect-the-environment-2020-2021.pdf?src=climate-change
www.altria.com/about-altria/our-voice-and-actions/scotus-title-vII-ruling-support-and-va-values-act
www.altria.com/about-altria/our-leadership/jon-moore
www.altria.com/Overlays/Companies-and-Brands/CRONOS
www.altria.com/moving-beyond-smoking?src=our-approach-to-harm-reduction
www.altria.com/about-altria/government-affairs/political-contributions-b
www.altria.com/Overlays/Companies-and-Brands/AGDC
www.altria.com/-/media/Project/Altria/Altria/responsibility/corporate-responsibility-reports/protect-the-environment-2020-2021.pdf?src=environmental-management-framework
www.altria.com/about-altria/our-voice-and-actions/preserving-the-waterway-that-helped-build-america
www.altria.com/-/media/Project/Altria/Altria/responsibility/environmental-management/Environmental_Management_Website_Data_Supplement.pdf
soprweb.senate.gov/index.cfm?event=getFilingDetails&filingID=61BCC56C-7DFF-4045-AC3F-D04F76D5C6F4&filingTypeID=60
4consumerchoice.com/
soprweb.senate.gov/index.cfm?event=getFilingDetails&filingID=89A46C68-F4EA-4CA0-8368-E6A137D068A9&filingTypeID=69
www.altria.com/about-altria/government-affairs/public-policy-positions/protecting-the-environment
www.altria.com/about-altria/our-leadership/charlie-whitaker
www.altria.com/moving-beyond-smoking/reduce-the-harm-of-tobacco-products?src=2025-focus-areas-goals
www.altria.com/about-altria/board-of-directors-and-corporate-governance/board-of-directors-at-a-glance/william-f-gifford-jr
www.ussmokeless.com/products/smokeless-tobacco-msa
https://www.growthopps.org/
www.altria.com/about-altria/our-voice-and-actions/juneteenth-day-of-healing
www.altria.com/-/media/Project/Altria/Altria/responsibility/corporate-responsibility-reports/protect-the-environment-2020-2021.pdf?src=protect-the-environment
soprweb.senate.gov/index.cfm?event=getFilingDetails&filingID=950E26B4-D8E2-45C8-A9E5-B00B8B60272E&filingTypeID=60
www.altria.com/about-altria
www.altria.com/Overlays/Companies-and-Brands/ALCS
www.altria.com/-/media/Project/Altria/Altria/about-altria/federal-regulation-of-tobacco/regulatory-filings/documents/FDA-Center-for-Tobacco-Products-Education-Campaign.pdf
www.altria.com/-/media/Project/Altria/Altria/responsibility/at-a-glance/focus-areas-and-goals/2020-2021-cr-engage-and-lead-responsibly-report.pdf?src=responsibility-at-a-glance
www.altria.com/moving-beyond-smoking?src=communicating-tobacco-health-effects
www.cdc.gov/mmwr/volumes/69/wr/mm6950a1.htm
www.altria.com/Overlays/Companies-and-Brands/Altria
tobaccoissues.com/
www.altria.com/responsibility/prevent-underage-use
www.altria.com/responsibility/prevent-underage-use/underage-access-prevention
www.altria.com/terms-of-use
www.altria.com/about-altria/board-of-directors-and-corporate-governance/board-of-directors-at-a-glance/george-munoz
investor.altria.com/annual-report-proxy-statement-annual-meeting/default.aspx?src=topnav
investor.altria.com/stock-performance/dividend-information/default.aspx?src=homepage
investor.altria.com/press-releases/news-details/2022/Altria-Reports-2021-Fourth-Quarter-and-Full-Year-Results-Provides-2022-Full-Year-Earnings-Guidance/default.aspx
