www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/template-d--product-safety-regulatory-3party-ndarev-11252019-anthesis.docx?la=fr-ca
www.Kimberly-Clark.com/ru-ru/brands/adult-care
www.kimberly-clark.com/pt-br/responsibility/annualreports
www.Kimberly-Clark.com/company/supplier-link/standards-and-requirements/supplier-requirements/anti-corruption-compliance
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-polish.pdf?la=pt-br
www.goodnites.com/es-us/privacy
www.sustainability2022.com/en/five-priorities/energy-and-climate
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-english.pdf?la=fr-ca
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-italian.pdf?la=en-us
www.Kimberly-Clark.com/fr-ca/company/supplier-link/standards-and-requirements/social-compliance
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-hebrew.pdf?la=es-us
www.Kimberly-Clark.com/ru-ru/brands/family-care
www.Kimberly-Clark.com/company/leadership
3cba

www.kimberly-clark.com/fr-ca/brands/our-brands
www.huggies.com/en-us/privacy-policy
www.Kimberly-Clark.com/brands/adult-care
www.Kimberly-Clark.com/pt-br/company/supplier-link/supplier-collaboration
www.Kimberly-Clark.com/en-ca
www.Kimberly-Clark.com/en-us/responsibility/diversity-and-inclusion
www.Kimberly-Clark.com/fr-ca/brands/residuals
www.kcprofessional.com/en-us
www.kimberly-clark.com/pt-br/esg/2030-ambition
www.Kimberly-Clark.com/pt-br/company/supplier-link/invoice-requirement
www.Kimberly-Clark.com/en-us/company/supplier-link/standards-and-requirements/social-compliance/anti-trust-compliance
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-thai.pdf?la=es-us
www.Kimberly-Clark.com/es-us/company/supplier-link/standards-and-requirements/social-compliance/business-gratuities
www.Kimberly-Clark.com/-/media/kimberly/pdf/eu-terms/sk-tsandcs.pdf?la=en-us
www.Kimberly-Clark.com/fr-ca/company/supplier-link/standards-and-requirements/stewardship
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/p2p-supplier-portal-procurement-policy.pdf?la=en-us
www.kotex.co.za
www.Kimberly-Clark.com/fr-ca/investors/corporate-governance/contact-the-board
www.kimberly-clark.com/responsibility/annualreports
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/north-america-region--specific--payment-receipt-info.pdf?la=fr-ca
www.Kimberly-Clark.com/en-ca/covid-19/carin
qa1.global.kimberly-clark.com/en/investors/corporate-governance/code-of-conduct
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2012/2012-report---brazil-english.pdf
www.kimberly-clark.com/es-us/brands/feminine-care
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_spanish-la_umbracofile.pdf?la=en-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-thai.pdf?la=fr-ca
www.Kimberly-Clark.com/es-us/-/media/kimberly/pdf/innovation/productevol_facialtissue_umbracofile.pdf
www.kimberly-clark.com/en-us/brands/feminine-care
www.Kimberly-Clark.com/-/media/kimberly/pdf/audit-committee-charter.pdf?la=ru-ru
www.Kimberly-Clark.com/-/media/kimberly/pdf/annual-report/2009-annual-report_umbracofile.pdf
www.Kimberly-Clark.com/en-us/brands/ingredients
www.Kimberly-Clark.com/es-us/brands/baby-and-child-care
www.Kimberly-Clark.com/fr-ca/company/patents
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/na-supplier-requirements-list.pdf?la=es-us
www.kimberly-clark.com.uy/
www.kimberly-clark.com/en-ca/company/patents
www.youtube.com/watch?v=2zCbuPVIgYE&feature=youtu.be
www.Kimberly-Clark.com/pt-br/company/supplier-link/standards-and-requirements/social-compliance/anti-trust-compliance
www.instagram.com/kcc
www.Kimberly-Clark.com/fr-ca/esg/social-impact
www.kimberly-clark.com/en-ca/ourprivacyvalues
investor.kimberly-clark.com/stock-information/investment-calculator
www.Kimberly-Clark.com/en/esg/social-impact
www.kcprofessional.es/marcas/wypall
www.Kimberly-Clark.com/-/media/kimberly/pdf/ingredients/st-14665-kimberly-clark-restricted-substances-list_june-2020.pdf?la=en
www.Kimberly-Clark.com/ru-ru
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-russian.pdf?la=es-us
www.cottonelle.com/en-us/privacy-policy
www.Kimberly-Clark.com/en-us/terms-and-conditions-es-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_simplified-chinese_umbracofile.pdf?la=pt-br
www.bgca.org/about-us/Boys-Girls-Clubs-Response-to-COVID-19
www.Kimberly-Clark.com/pt-br/sustainability2022/supplychain
qa1.global.kimberly-clark.com/en-ca/locations
kimberlyclark.gcs-web.c
www.kimberly-clark.com/en-au/ 
www.kimberly-clark.com/ru-ru/esg/strategy
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/kc-codeofconduct-en.pdf?la=fr-ca
customers.taulia.com/kimberly-clark/
www.huggies.co.in
www.kimberly-clark.com/en-us/company/leadership
www.kimberly-clark.com/ru-ru/esg/smallest-footprint
www.Kimberly-Clark.com/ru-ru/company/technology-licensing
www.Kimberly-Clark.com/-/media/kimberly/pdf/annual-report/2008-annual-report_umbracofile.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_korean_umbracofile.pdf?la=pt-br
kimberlyclark.gcs-web.com/news-releases/news-release-details/kimberly-clark-announces-year-end-2021-results-and-2022-outlook
www.kimberly-clark.com/ru-ru/sitemap
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-turkish.pdf?la=fr-ca
www.Kimberly-Clark.com/fr-ca/brands/not-in-our-products
www.amazon.it/stores/Kleenex/Paginaprincipale/page/C8BA2F10-6C80-4F5C-B121-CD6200CF1F3E
www.kimberly-clark.com/en-us/brands/our-brands
www.Kimberly-Clark.com/ru-ru/company/our-vision
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_traditional-chinese_umbracofile.pdf?la=fr-ca
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-german.pdf?la=ru-ru
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-english.pdf?la=en-us
www.Kimberly-Clark.com/fr-ca/company/leadership
www.Kimberly-Clark.com/en-us/responsibility/social-compliance
www.Kimberly-Clark.com/en-us/trafficking-statement
www.Kimberly-Clark.com/pt-br/brands/not-in-our-products
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/p2p-supplier-portal-procurement-policy.pdf?la=pt-br
www.Kimberly-Clark.com/responsibility/ethics-governance
www.Kimberly-Clark.com/ru-ru/esg/smallest-footprint
www.Kimberly-Clark.com/es-us/-/media/kimberly/pdf/investors/guidelines_hiringemployeesofauditors_umbracofile.pdf
www.lakotex.com.ar/
www.vivatowels.ca/fr/PrivacyPolicy.aspx
www.kimberly-clark.com/es-us/trafficking-statement
www.kimberly-clark.com/ru-ru/responsibility/ethics-governance
www.viveplenitud.com/
www.
www.kimberly-clark.com/en-ca/esg/2030-goals
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2017/2017-report.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_malay_umbracofile.pdf?la=es-us
www.kimberly-clark.com/contact-us.aspx
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/k-c-by-laws-4-29-21.pdf?la=pt-br
www.ifraorg.org/
www.Kimberly-Clark.com/-/media/kimberly/pdf/eu-terms/cz-tsandcs-1612.pdf?la=en-us
www.kimberly-clark.com/fr-ca/esg/social-impact
www.huggies.com/es-us/politica-de-privacidad
www.Kimberly-Clark.com/fr-ca/brands/safety-commitment
www.kimberly-clark.com/pt-br/esg/smallest-footprint/water
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2012/2012-report.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/ethics-and-governance/fiberprocurementpolicy.pdf?la=fr-ca
www.facebook.com/KleenexSA/
www.Kimberly-Clark.com/fr-ca/company/supplier-link/procure-to-pay
www.Kimberly-Clark.com/company/supplier-link/supplier-collaboration
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-english.pdf?la=es-us
www.Kimberly-Clark.com/ru-ru/company/supplier-link/receiving-payment
www.Kimberly-Clark.com/fr-ca/company/innovation
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_thai_umbracofile.pdf?la=pt-br
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/mdc-committee-charter.pdf?la=ru-ru
www.linkedin.com/company/kimberly-clark?trk
www.kimberly-clark.com/en-ca/esg/smallest-footprint/water
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2011/2011-report.pdf
www.Kimberly-Clark.com/fr-ca/-/media/kimberly/pdf/investors/compliantprocedures_umbracofile.pdf
www.Kimberly-Clark.com/pt-br/company/supplier-link/responsible-supply-chain
www.huggies.com/
www.Kimberly-Clark.com/ru-ru/responsibility/sustainability2022
www.Kimberly-Clark.com/en-us/company/employees
www.Kimberly-Clark.com/es-us/investors/corporate-governance
www.Kimberly-Clark.com/fr-ca/-/media/kimberly/pdf/innovation/productevol_femininepads_umbracofile.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2012/2012-report---central-america--caribbean-english.pdf
csr.yuhan-kimberly.co.kr/resources_2020/file/yk_2016_en.pdf
www.kimberly-clark.com/fr-ca/trafficking-statement
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-polish.pdf?la=es-us
www.Kimberly-Clark.com/pt-br/company/supplier-link/risk-management
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/compliantprocedures_umbracofile.pdf?la=es-us
www.kimberly-clark.com/en-ca/esg/smallest-footprint/forests
www.kimberly-clark.com/en/responsibility/sustainability2022
www.Kimberly-Clark.com/pt-br/company/supplier-link/standards-and-requirements/social-compliance/business-gratuities
www.huggies.com
www.kimberly-clark.com/es-us/company/supplier-link/supplier-collaboration
www.Kimberly-Clark.com/fr-ca/responsibility/diversity-and-inclusion
www.kimberly-clark.com/en-us/company/supplier-link/procure-to-pay
www.Kimberly-Clark.com/en-ca/covid-19/caring-for-our-people
www.Kimberly-Clark.com/-/media/kimberly/pdf/ingredients/st-14665-kimberly-clark-restricted-substances-list_june-2020.pdf?la=es
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_portuguese_umbracofile.pdf?la=pt-br
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_spanish-la_umbracofile.pdf?la=es-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2013/2013-report---columbia.pdf
www.kimberly-clark.com/es-us/esg/strategy
www.kimberly-clark.com/en-ca/esg/smallest-footprint/climate
www.Kimberly-Clark.com/ru-ru/brands/not-in
www.kimberly-clark.com/fr-ca/esg/smallest-footprint/plastics
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2007/2007-report.pdf
www.kcprofessional.fr/
www.Kimberly-Clark.com/en-us/company/supplier-link/receiving-payment
www.Kimberly-Clark.com/investors/corporate-governance
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/apac_invoicing-requirements_country-specifics_refresh2020.pdf?la=ru-ru
kimberlyclark.wd1.myworkdayjobs.com/EMEA/1/refreshFacet/318c8bb6f553100021d223d9780d30be
www.kimberly-clark.com/ru-ru/esg/smallest-footprint/forests
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-slovenian.pdf?la=es-us
www.Kimberly-Clark.com/es/esg/social-impact
www.Kimberly-Clark.com/ru/brands/our-brands
www.Kimberly-Clark.com/pt-br/investors/corporate-governance/stock-option-purchases
spr.ly/61831voJT
kimberlyclark.gcs-web.com/news-releases/news-release-details/kimberly-clark-and-unicef-partner-help-2-million-babies-and
www.huggies.it/prodotti/huggies-little-swimmers
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_thai_umbracofile.pdf?la=es-us
www.Kimberly-Clark.com/es-us/brands/preservatives
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-spanish.pdf?la=es-us
www.Kimberly-Clark.com/fr-ca/brands/kc-professional
www.Kimberly-Clark.com/ru-ru/comp
www.Kimberly-Clark.com/pt-br/company/leadership
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/k-c-supplier-code-of-conduct-_english-and-spanish.pdf?la=pt-br
www.Kimberly-Clark.com/saas-agr
7ff1
eement
www.Kimberly-Clark.com/fr-ca/-/media/kimberly/pdf/innovation/productevol_disposablediaper_umbracofile.pdf
investor.kimberly-clark.com/financial
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-german.pdf?la=pt-br
csr.yuhan-kimberly.co.kr/resources_2020/file/yk_2010_en.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/annual-report/2018_annualreport_umbracofile.pdf
www.kimberly-clark.com/ru-ru/esg/2030-ambition
www.Kimberly-Clark.com/locations
www.Kimberly-Clark.com/en-za/southafrica/ourteams
www.Kimberly-Clark.com/covid-19/caring-for-our-consumers
www.Kimberly-Clark.com/-/media/kimberly/pdf/covid-19/04-22---covid-19-response-infographic---1q-earnings.pdf?la=en-us
www.Kimberly-Clark.com/en-ca/covid-19/caring-for-our-consumers
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-polish.pdf?la=en-us
www.Kimberly-Clark.com/company/leadership
www.kimberly-clark.com.py/
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_malay_umbracofile.pdf?la=en-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-chinese-traditional.pdf?la=pt-br
www.Kimberly-Clark.com/responsibility/social-impact
investor.kimberly-clark.com/news-releases/news-release-details/diaper-need-continues-impact-1-3-us-families-according-new-study
www.Kimberly-Clark.com/fr-ca/company/supplier-link/standards-and-requirements/social-compliance/sustainability-policies
kimberlyclark
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-indonesian.pdf?la=pt-br
www.Kimberly-Clark.com/-/media/kimberly/pdf/southafrica/certificate--kimberlyclark-of-south-africa-pty-ltd-bdo11853060521.pdf
www.Kimberly-Clark.com/en-us/company/supplier-link/standards-and-requirements/stewardship
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/k-c-by-laws-4-29-21.pdf?la=fr-ca
www.Kimberly-Clark.com/es-us/company/supplier-link/procure-to-pay-portal
www.kimberly-clark.com/es-us/esg/2030-ambition
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/na-supplier-requirements-list.pdf?la=pt-br
www.3blmedia.com/news/producing-essentials-and-leading-inclusion-conversations-about-advice
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-arabic.pdf?la=es-us
www.Kimberly-Clark.com/ru-ru/-/media/kimberly/pdf/innovation/productevol_femininepads_umbracofile.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2015/2015-report---australia-and-new-zealand.pdf
www.es.scottex.com
www.Kimberly-Clark.com/en-us/covid-19/caring-for-those-in-need/childcare-for-essential-workers
www.Kimberly-Clark.com/en-us/company/supplier-link/procure-to
www.Kimberly-Clark.com/pt-br/-/media/kimberly/pdf/audit-committee-charter.pdf
kimberlyclark.gcs-web.com/financial/sec-filings
www.Kimberly-Clark.com/pt/brands/our-brands
www.Kimberly-Clark.com/ru-ru/sustainability2022/energyclimate
www.kimberly-clark.com/en-us/terms-of-use
www.softexindonesia.com/ 
www.youtube.com/user/Kimberly
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2007/2007-executive-summary.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/audit-committee-charter.pdf?la=fr-ca
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-chinese-traditional.pdf?la=fr-ca
www.Kimberly-Clark.com/-/media/kimberly/pdf/ingredients/st-14665-kimberly-clark-restricted-substances-list_june-2020.pdf?la=pt-br
www.Kimberly-Clark.com/en-us/sustainability2022/supplychain
www.Kimberly-Clark.com/ru-ru/-/media/kimberly/pdf/innovation/productevol_papertowel_umbracofile.pdf
www.kimberly-clark.com/en/company/supplier-link/standards-and-requirements/social-compliance
www.Kimberly-Clark.com/fr-ca/investors/corporate-governance/stock-option-purchases
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_traditional-chinese_umbracofile.pdf?la=en-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_hebrew_umbracofile.pdf?la=fr-ca
www.depend.com.es/principal/
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-chinese-simplified.pdf?la=ru-ru
www.Kimberly-Clark.com/-/media/kimberly/pdf/annual-report/2014_annualreport_umbracofile.pdf
csr.yuhan-kimberly.co.kr/resources_2020/file/yk_2019_en.pdf
www.kimberly-clark.com/en-us/esg/social-impact
www.kimberly-clark.com/fr-ca/sitemap
kimberlyclark.gcs-web.com/static-files/64439a04-c754-4cd4-ae60-19119aff2f6d
www.kimberly-clark.com/en-ca/company/technology-licensing
www.careersatkc.com/en/spain
www.Kimberly-Clark.com/es-us/company/supplier-link/supplier-collaboration
www.Kimberly-Clark.com/pt-br/-/media/kimberly/pdf/investors/guidelines_hiringemployeesofauditors_umbracofile.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-english.pdf?la=pt-br
www.Kimberly-Clark.com/pt-br/sustainability2022/energyclimate
www.kimberly-clark.com/fr-ca/esg/smallest-footprint
www.Kimberly-Clark.com/-/media/kimberly/pdf/esg/smallest-footprint/climate/kimberly-clark-2030-ambitions-carbon.pdf?la=en-us
www.kimberly-clark.com/en-us/investors/individual-investor-services
www.Kimberly-Clark.com/fr-ca/-/media/kimberly/pdf/innovation/productevol_toilettissue_umbracofile.pdf
www.kimberly-clark.com/pt-br/responsibility/social-impact/intimus-ela-pode-iniciativa
www.Kimberly-Clark.com/es-es/company/about-us
www.Kimberly-Clark.com/investors/corporate-governance/stock-option-purchases
www.3blmedia.com/news/kimberly-clark-earns-perfect-score-human-rights-campaign-foundations-2022-corporate-equality
www.Kimberly-Clark.com/-/media/kimberly/pdf/slavery-and-human-trafficing/modern-slavery-statement-uk-board---26-july-2021-signed-kt.pdf?la=en-us
www.Kimberly-Clark.com/en-us/brands/fragrances
www.Kimberly-Clark.com/fr-ca/company/technology-licensing
www.Kimberly-Clark.com/-/media/kimberly/pdf/eu-terms/de-tsandcs-1612.pdf?la=en-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/ethics-and-governance/fiberprocurementpolicy.pdf?la=es-us
www.kleenex.com/en-ca/privacy-policy
www.kimberly-clark.com/en-us/company/supplier-link/standards-and-requirements
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/lao-invoicing-requirements-country-specific_engspan-_refresh2020.pdf?la=pt-br
www.youtube.com/user/K
www.Kimberly-Clark.com/en-us/brands/adhesive
www.computershare.com/us
www.huggies.es/
www.kimberly-clark.com/fr-ca/esg/strategy
www.Kimberly-Clark.com/responsibility/social-impact/kotex-she-can-initiative
www.huggies.co.za/
www.kimberly-clark.com/pt/contact-us
www.kimberly-clark.com/en-ca/brands/feminine-care
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/ncg-committee-charter---revised-11-19-20.pdf?la=ru-ru
www.Kimberly-Clark.com/en-us/company/supplier-link/standards-and-requirements/material-and-product-specific-requirements
www.Kimberly-Clark.com/en-ca/covid-19/caring-for-those-in-need
www.kimberly-clark.com/en-ca/esg/smallest-footprint
www.kimberly-clark.com/en-us/supplier-diversity
kimberlyclark.wd1.myworkdayjobs.com/EMEA
www.Kimberly-Clark.com/pt-br/company/supplier-link
www.kimberly-clark.com/en-us/brands/safety-commitment
www.depend.it/home/
www.kimberly-clark.com/ru-ru/contact-us
www.kimberly-clark.com/pt-br/privacy
www.Kimberly-Clark.com/ru-ru/-/media/kimberly/pdf/investors/mdc-committee-charter.pdf
www.Kimberly-Clark.com/es-us/brands/feminine-care
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2005/2005-report.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-portuguese-brazil.pdf?la=ru-ru
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2004/2004-report.pdf
www.3blmedia.com/news/what-would-wonder-woman-do
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-polish.pdf?la=ru-ru
www.Kimberly-Clark.com/es-us/brands/adult-care
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/k-c-certificate-of-incorporation-4-29-21.pdf?la=pt-br
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-arabic.pdf?la=fr-ca
www.Kimberly-Clark.com/en-ca/covid-19/caring-for-those-in-need/huggies-covid-19-relief-efforts
www.Kimberly-Clark.com/es/esg/2030-ambition
www.Kimberly-Clark.com/fr-ca/-/media/kimberly/pdf/investors/ncg-committee-charter---revised-11-19-20.pdf
www.kimberly-clark.com/en-ca/sitemap
www.Kimberly-Clark.com/en-us/
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_simplified-chinese_umbracofile.pdf?la=en-us
www.kimberly-clark.com/en-ca/brands/adult-care
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/template-d--product-safety-regulatory-3party-ndarev-11252019-anthesis.docx?la=pt-br
www.Kimberly-Clark.com/es-us/company/unsolicited-ideas
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-hebrew.pdf?la=en-us
www.Kimberly-Clark.com/ru/responsibility/annualreports
www.Kimberly-Clark.com/fr-ca/brands/our-brands
www.Kimberly-Clark.com/ru-ru/investors/individual-investor-services
www.Kimberly-Clark.com/ru-ru/company/supplier-link/invoicing
kimberlyclark.gcs-web.com/news-releases/news-release-details/huggiesr-donate-five-million-diapers-national-diaper-bank
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-german.pdf?la=es-us
www.Kimberly-Clark.com/ru-ru/investors/annual-reports
www.Kimberly-Clark.com/fr-ca/company/supplier-link/receiving-payment
www.kimberly-clark.com/es-us/brands/family-care
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-german.pdf?la=fr-ca
www.Kimberly-Clark.com/pt-br/company/unsolicited-ideas
www.kimberly-clark.com/pt-br/esg
csr.yuhan-kimberly.co.kr/resources_2020/file/yk_2017_en.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-hebrew.pdf?la=ru-ru
www.Kimberly-Clark.com/en-us/investors/corporate-governance/code-of-conduct
www.Kimberly-Clark.com/es-us/company/supplier-link/standards-and-requirements/social-compliance
www.kimberly-clark.com/es-us/brands/preservatives
twitter.com/KCCorp
www.kimberly-clark.com/en-us/responsibility/kc-foundation
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_thai_umbracofile.pdf?la=en-us
www.kimberly-clark.com/en-us/esg/smallest-footprint/water
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-portuguese-brazil.pdf?la=en-us
www.Kimberly-Clark.com/ru-ru/brands/fragrances
www.Kimberly-Clark.com/fr-ca/company/supplier-link/invoicing
www.Kimberly-Clark.com/en-us/company/supplier-link/standards-and-requirements/quality
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-polish.pdf?la=fr-ca
www.Kimberly-Clark.com/pt-br/brands/feminine-care
www.Kimberly-Clark.com/fr-ca/sustainability2022/supplychain
www.Kimberly-Clark.com/404.aspx?item=web%3a%7bF15ED695-05BB-4CBA-AAE3-FD20294AD051%7d%40ru-RU
www.Kimberly-Clark.com/en-us/esg/policies/antitrust-and-competition-compliance
www.Kimberly-Clark.com/en-us/brands/adult-care
www.Kimberly-Clark.com/en-us/esg/2030-ambition
www.kimberly-clark.com/en-us/esg/2030-goals
www.Kimberly-Clark.com/-/media/kimberly/pdf/eu-terms/it-tsandcs-1612.pdf?la=en-us
www.Kimberly-Clark.com/ru-ru/investors/investor-contacts
www.careersatkc.com
www.kimberly-clark.com/en-ca/company/supplier-link/standards-and-requirements
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/emea_invoicing-requirements_refresh2020.pdf?la=fr-ca
www.Kimberly-Clark.com/ru-ru/company/patents
www.Kimberly-Clark.com/es-us/-/media/kimberly/pdf/innovation/productevol_femininepads_umbracofile.pdf
www.Kimberly-Clark.com/pt-br/-/media/kimberly/pdf/investors/kimberly-clark-corporate-governance-policies.pdf
www.Kimberly-Clark.com/fr-ca/brands/ingredients
www.Kimberly-Clark.com/brands/residuals
www.kimberly-clark.com/pt-br/responsibility/social-impact/toilets-change-lives
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2015/2015-report---central-america-and-caribbean.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_english_umbracofile.pdf?la=fr-ca
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_spanish-la_umbracofile.pdf?la=fr-ca
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/kc-codeofconduct-en.pdf?la=ru-ru
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-chinese-simplified.pdf?la=fr-ca
www.pull-ups.com/en-ca/privacy-policy
www.Kimberly-Clark.com/es-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2009/2009-report.pdf
www.kimberly-clark.com/es-us/responsibility/social-impact/toilets-change-lives
www.kimberly-clark.com/es-us/esg
www.kleenex.es/
www.Kimberly-Clark.com/unsubscribe
www.kimberly-clark.com/unsubscribe.aspx
www.Kimberly-Clark.com/de-de/germany
www.kimberly-clark.com/es-us/esg/smallest-footprint/plastics
www.Kimberly-Clark.com/es-us/company/about-us
www.Kimberly-Clark.com/brands/family-care
www.kimberly-clark.com/en-ca/responsibility/social-impact/toilets-change-lives
www.Kimberly-Clark.com/-/media/kimberly/pdf/ingredients/st-14665-kimberly-clark-restricted-substances-list_june-2020.pdf?la=fr-ca
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-indonesian.pdf?la=ru-ru
www.kimberly-clark.com/en-ca/company/employees
www.Kimberly-Clark.com/ru-ru/-/media/kimberly/pdf/innovation/productevol_disposabletrainingpants_umbracofile.pdf
www.kimberly-clark.com/es-us/responsibility/ethics-governance
www.Kimberly-Clark.com/fr-ca/esg/policies/business-gratuities
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/k-c-by-laws-4-29-21.pdf?la=es-us
sciencebasedtargets.org/
www.Kimberly-Clark.com/es-us/brands/fragrances
www.cottonelle.com/en-us/share-a-square
www.littleswimmers.ch
www.cloudflare.com/sign-up?utm_source=email_protection
www.Kimberly-Clark.com/es-us/-/media/kimberly/pdf/innovation/productevol_disposabletrainingpants_umbracofile.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/ncg-committee-charter---revised-11-19-20.pdf?la=fr-ca
www.scottbrand.com/es-us/politica-de-privacidad
www.Kimberly-Clark.com/investors/corporate-governance/code-of-conduct
www.kimberlyclarkprofessional.com/index.html
www.Kimberly-Clark.com/en-us/terms-of-use
qa1.global.kimberly-clark.com/pt/investors/corporate-governance/code-of-conduct
www.Kimberly-Clark.com/pt-br/-/media/kimberly/pdf/innovation/productevol_disposablediaper_umbracofile.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/lao-invoicing-requirements-country-specific_engspan-_refresh2020.pdf?la=ru-ru
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_portuguese_umbracofile.pdf?la=en-us
www.Kimberly-Clark.com/en-us/company/supplier-link/procure-to-pay-portal
www.Kimberly-Clark.com/en-us/company/supplier-link/risk-management
www.Kimberly-Clark.com/fr-ca/company/supplier-link/procure-to-pay-portal
www.Kimberly-Clark.com/en-us/company/supplier-link/invoicing
www.Kimberly-Clark.com/fr-ca/company/our-vision
www.kcprofessional.es/
www.Kimberly-Clark.com/locations/india/careers
www.kimberly-clark.com/es-us/company/patents
www.sustainability2022.com/five-priorities/social-impact
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/guidelines_hiringemployeesofauditors_umbracofile.pdf?la=pt-br
www.scottbrand.com/en-us/privacy-policy
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-turkish.pdf?la=pt-br
www.Kimberly-Clark.com/es-us/company/supplier-link/standards-and-requirements/supplier-requirements/anti-corruption-compliance
www.Kimberly-Clark.com/es-us/responsibility/sustainability2022
kimberlyclark.gcs-web.com/
www.Kimberly-Clark.com/fr-ca/company/supplier-link/supplier-collaboration
www.sustainability2022.com/our-stories/women-ignite-for-change
kcc-rcp.et
21b6
q.com/RCPProd/reliance
www.kimberly-clark.com/en-ca/esg/strategy
handtohold.org/
www.Kimberly-Clark.com/-/media/kimberly/pdf/kc-tcfd-2021-final.pdf
www.Kimberly-Clark.com/en-us/brands/safety-commitment
www.Kimberly-Clark.com/pt-br/company/our-vision
www.Kimberly-Clark.com/ru-ru/company/supplier-link/invoice-requirements
www.littleswimmers.fr/
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2020/k-c-2020-global-sustainability-report.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-english.pdf?la=ru-ru
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/kimberly-clark-sustainability-report_2016_forest-and-fiber.pdf?la=es-us
www.kimberly-clark.com/es-us/brands/residuals
www.Kimberly-Clark.com/es-us/-/media/kimberly/pdf/innovation/productevol_papertowel_umbracofile.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-turkish.pdf?la=en-us
www.Kimberly-Clark.com/es-us/company/supplier-link/receiving-payment
www.Kimberly-Clark.com/fr-ca/esg/2030-ambition
www.Kimberly-Clark.com/fr-ca/-/media/kimberly/pdf/innovation/productevol_disposabletrainingpants_umbracofile.pdf
3blmedia.com/News/Kimberly-Clark-Earns-Perfect-Score-Human-Rights-Campaigns-2018-Corporate-Equality-Index
kimberlyclark.gcs-web.com/rss-
www.Kimberly-Clark.com/pt-br/esg/2030-ambition
www.Kimberly-Clark.com/brands/fragrances
www.kimberly-clark.com/es-us/accessibility
www.kimberly-clark.com/es-us/esg/social-impact
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-korean.pdf?la=fr-ca
www.Kimberly-Clark.com/es/brands/our-brands
www.Kimberly-Clark.com/pt-br/brands/kc-professional
www.kimberly-clark.com/en-us/PrivacyPolicy
www.Kimberly-Clark.com/ru-ru/brands/kc-professional
www.kimberly-clark.com/en-us/company/employees
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_korean_umbracofile.pdf?la=en-us
www.Kimberly-Clark.com/en-us/brands/feminine-care
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/mdc-committee-charter.pdf?la=pt-br
www.kimberly-clark.com/es-us/locations
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-vietnamese.pdf?la=pt-br
www.Kimberly-Clark.com/en/esg/smallest-footprint
support.cloudflare.com/hc/en-us/articles/200170016-What-is-Email-Address-Obfuscation-
www.Kimberly-Clark.com/es-us/brands/our-brands
www.Kimberly-Clark.com/pt-br/company/supplier-link/standards-and-requirements/social-compliance/sustainability-policies
www.kimberly-clark.com/en-ca/company/supplier-link
www.Kimberly-Clark.com/investors/annual-reports
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-korean.pdf?la=en-us
www.Kimberly-Clark.com/pt-br/company/supplier-link/standards-and-requirements/social-compliance/supply-chain-act
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/guidelines_hiringemployeesofauditors_umbracofile.pdf?la=es-us
www.kleenex.ch
www.kimberly-clark.com/ru-ru/responsibility/social-impact/toilets-change-lives
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/template-d--product-safety-regulatory-3party-ndarev-11252019-anthesis.docx?la=en-us
www.Kimberly-Clark.com/es-es/spain/salamanca
www.Kimberly-Clark.com/-/media/kimberly/pdf/esg/smallest-footprint/climate/kimberly-clark-2019-performance-climate.pdf
www.Kimberly-Clark.com/fr-ca/brands/preservatives
www.Kimberly-Clark.com/fr-ca/company/supplier-link/supplier-diversity
www.Kimberly-Clark.com/es-us/company/supplier-link/standards-and-requirements/st
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/ncg-committee-charter---revised-11-19-20.pdf?la=es-us
www.kimberly-clark.com/f
www.Kimberly-Clark.com/ru-ru/investors/corporate-governance/stock-option-purchases
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_english_umbracofile.pdf?la=es-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-arabic.pdf?la=ru-ru
www.Kimberly-Clark.com/marketing-standards-terms
www.Kimberly-Clark.com/en-us/company/supplier-link/supplier-portals
www.Kimberly-Clark.com/404.aspx?item=web%3a%7bF15ED695-05BB-4CBA-AAE3-FD20294AD051%7d%40es-US
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-chinese-traditional.pdf?la=ru-ru
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/kimberly-clark-corporate-governance-policies.pdf
www.Kimberly-Clark.com/company/supplier-link
www.Kimberly-Clark.com/en-us/esg/smallest-footprint
www.Kimberly-Clark.com/pt-br/-/media/kimberly/pdf/investors/k-c-by-laws-4-29-21.pdf
www.Kimberly-Clark.com/fr-ca/-/media/kimberly/pdf/innovation/productevol_facialtissue_umbracofile.pdf
www.Kimberly-Clark.com/en-za/company/about-us
www.Kimberly-Clark.com/pt-br/investors/investor-contacts
www.Kimberly-Clark.com/es-us/-/media/kimberly/pdf/innovation/productevol_disposablediaper_umbracofile.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2010/2010-report.pdf
www.Kimberly-Clark.com/pt-br/company/innovation
www.Kimberly-Clark.com/ru-ru/brands/ingredients
www.Kimberly-Clark.com/es-us/sustainability2022/energyclimate
www.Kimberly-Clark.com/es-us/company/employees
www.Kimberly-Clark.com/es-us/brands/family-care
www.Kimberly-Clark.com/es-us/esg/policies/business-gratuities
www.Kimberly-Clark.com/-/media/kimberly/pdf/ingredients/st-14665-kimberly-clark-restricted-substances-list_june-2020.pdf?la=en-us
www.ubykotex.com/en-us/privacy/
www.Kimberly-Clark.com/fr-ca/investors/corporate-governance/hedging-and-pledging-policy
www.kimberly-clark.com/en-us/responsibility/social-impact/kotex-she-can-initiative
www.kimberly-clark.com/en-ca/responsibility/annualreports
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-dutch.pdf?la=fr-ca
kimberlyclark.gcs-web.com/email-alerts
www.Kimberly-Clark.com/ru-ru/company/innovation
www.Kimberly-Clark.com/pt-br/responsibility/sustainability2022
www.Kimberly-Clark.com/pt-br/company/about-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/apac_invoicing-requirements_country-specifics_refresh2020.pdf?la=pt-br
www.kimberly-clark.com/ru-ru/esg
www.kimberly-clark.com/fr-ca/responsibility/social-impact/toilets-change-lives
kimberlyclark.gcs-web.com/static-files/aa10468d-38e6-4f59-b38c-515dc7821ab1
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/kc-codeofconduct-en.pdf?la=es-us
www.Kimberly-Clark.com/pt/esg/smallest-footprint
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/lao-invoicing-requirements-country-specific_engspan-_refresh2020.pdf?la=fr-ca
www.kimberly-clark.com/en-ca/esg
www.kimberly-clark.com/ru-ru/responsibility/annualreports
www.youtube.com/channel/UCLY-Qb7yBjac1zwXdLhojsw
www.kimberly-clark.com/es-us/PrivacyPolicy
www.vivatowels.com/privacy-policy
www.kimberly-clark.com/en-us/esg/smallest-footprint/forests
www.Kimberly-Clark.com/pt-br/investors/corporate-governance
www.kimberly-clark.com/en-ca/responsibility/social-compliance
www.kimberly-clark.com/ru-ru/esg/smallest-footprint/climate
www.Kimberly-Clark.com/-/media/kimberly/pdf/eu-terms/pt-tsandcs.pdf?la=en-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-slovenian.pdf?la=ru-ru
www.Kimberly-Clark.com/brands/feminine-care
www.Kimberly-Clark.com/ru-ru/investors/corporate-governance
www.kimberly-clark.com/en-us/brands/residuals
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/mdc-committee-charter.pdf?la=fr-ca
www.kcprofessional.de
www.kimberly-clark.com/es-us/brands/ingredients
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-czech.pdf?la=pt-br
investor.kimberly-clark.com/financial/sec-filings
www.Kimberly-Clark.com/en-us/terms-and-conditions-en-us
www.kimberly-clark.com/en-us/company/supplier-link/supplier-portals
www.kimberly-clark.com/en-us/responsibility/sustainability2022
www.kleenex.com/en-us/privacy-policy
www.Kimberly-Clark.com/fr-ca/-/media/kimberly/pdf/investors/guidelines_hiringemployeesofauditors_umbracofile.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/k-c-certificate-of-incorporation-4-29-21.pdf?la=fr-ca
www.kimberly-clark.com/es-us/company/our-vision
www.kimberly-clark.com.tr/
www.Kimberly-Clark.com/pt-br/-/media/kimberly/pdf/investors/compliantprocedures_umbracofile.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_spanish-la_umbracofile.pdf?la=pt-br
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_english_umbracofile.pdf?la=pt-br
www.kimberly-clark.com/en-ca/company/supplier-link/supplier-diversity
www.inkinddirect.org/
www.Kimberly-Clark.com/ru-ru/investors/corporate-governance/contact-the-board
www.it.scottex.com/
kimberlyclark.gcs-web.com/news-releases/news-release-details/cottoneller-asks-americans-shareasquare-and-commits-1-million
www.Kimberly-Clark.com/en-us/company/supplier-link/standards-and-requirements/social-compliance/sustainability-policies
www.kimberly-clark.com/en-us/donotsellmyinfo
www.Kimberly-Clark.com/esg
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-vietnamese.pdf?la=es-us
www.Kimberly-Clark.com/ru-ru/company/unsolicited-ideas
www.fac
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_russian_umbracofile.pdf?la=es-us
qa1.global.kimberly-clark.com/-/media/kimberly/pdf/kotex-she-can-initiative/kotex_parentteacher.pdf?la=en
www.it.scottex.com/sostenibilita
csr.yuhan-kimberly.co.kr/resources_2020/file/yk_2012_en.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/eu-terms/nl-tsandcs-0810.pdf?la=en-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/north-america-region--specific--payment-receipt-info.pdf?la=ru-ru
www.Kimberly-Clark.com/es-us/esg/policies/anti-corruption-compliance
www.kimberly-clark.com/pt-br/responsibility/ethics-governance
www.kimberly-clark.com/en-us/esg/2030-ambition
www.kimberly-clark.com/pt-br/terms-of-use
www.poise.com/en-us/privacy-policy
www.kcprofessional.co.in
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-korean.pdf?la=ru-ru
www.Kimberly-Clark.com/ru-ru/company/supplier-link/supplier-diversity
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-czech.pdf?la=en-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-arabic.pdf?la=en-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2014/2014-report.pdf
www.drynites.it/
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2008/2008-executive-summary.pdf
www.Kimberly-Clark.com/ru-ru/brands/safety-commitment
www.kimberly-clark.com.cn/
www.Kimberly-Clark.com/es-us/esg/smallest-footprint
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-thai.pdf?la=en-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-portuguese-brazil.pdf?la=fr-ca
www.Kimberly-Clark.com/-/media/kimberly/pdf/eu-terms/es-tsandcs-0810.pdf?la=en-us
www.Kimberly-Clark.com/pt-br/company/technology-licensing
sciencebasedtargets.org/about-the-science-based-targets-initiative/
www.Kimberly-Clark.com/en-ca/covid-19/caring-for-those-in-need/u-by-kotex-donates-1m-products
www.Kimberly-Clark.com/-/media/kimberly/pdf/eu-terms/uk-tsandcs-1612_2015.pdf?la=en-us
3blmedia.com/News/Kimberly-Clark-Named-Working-Mothers-100-Best-Companies
www.huggieswindeln.de/
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-english.pdf
www.Kimberly-Clark.com/pt-br/investors/corporate-governance/code-of-conduct
www.Kimberly-Clark.com/ru-ru/ 
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-thai.pdf?la=ru-ru
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_hebrew_umbracofile.pdf?la=es-us
www.kimberly-clark.com/es-us/brands/baby-and-child-care
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-spanish.pdf?la=en-us
www.Kimberly-Clark.com/es/esg/smallest-footprint
www.kimberly-clark.com.tw/content/masterpage/Index.aspx 
investor.kimberly-clark.com/press-releases
www.Kimberly-Clark.com/ru/esg/smallest-footprint
www.yuhan-kimberly.co.kr/ 
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/kmb-2020-government-relations-disclosure.pdf?la=es-us
www.kimberly-clark.com/en-ca/company/supplier-link/procure-to-pay
www.Kimberly-Clark.com/pt-br/investors/corporate-governance/contact-the-board
www.kimberly-clark.com/es-us/ourprivacyvalues
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_hebrew_umbracofile.pdf?la=pt-br
www.Kimberly-Clark.com/en/brands/our-brands
csr.yuhan-kimberly.co.kr/resources_2020/file/yk_2013_en.pdf
www.Kimberly-Clark.com/de-ch/company/about-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/compliantprocedures_umbracofile.pdf?la=fr-ca
www.apprentissagedelaproprete.fr/
www.kimberly-clark.com/en-us/company/our-vision
www.Kimberly-Clark.com/en-us/covid-19/caring-for-those-in-need
www.kimberly-clark.com/es-us/company/supplier-link
www.Kimberly-Clark.com/pt-br/esg/social-impact
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2012/2012-report---argentina.pdf
www.Kimberly-Clark.com/en-us/sustainability2022/forestsfiber
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/lao-invoicing-requirements-country-specific_engspan-_refresh2020.pdf?la=es-us
www.Kimberly-Clark.com/responsibility/diversity-and-inclusion
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/ncg_committee_charter-revised_11-13-13_umbracofile.pdf?la=ru-ru
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/compliantprocedures_umbracofile.pdf?la=pt-br
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/emea_invoicing-requirements_refresh2020.pdf?la=en-us
www.kimberly-clark.com/pt-br/donotsellmyinfo
www.kimberly-clark.com/fr-ca/esg/2030-goals
www.Kimberly-Clark.com/es-es/investors/individual-investor-services
www.kimberly-clark.com/en-us/investors/corporate-governance
www.kimb
www.Kimberly-Clark.com/ru-ru/company/employees
www.kimberly-clark.com/en-us/investors/investor-contacts
www.Kimberly-Clark.com/saas-agreement
kimberlyclark.gcs-web.com/press-releases
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-chinese-simplified.pdf?la=en-us
handtohold.org/nicu-family-support/nicu-family-support-groups/
www.kimberly-clark.com/pt-br/esg/2030-goals
www.Kimberly-Clark.com/en-ca/company/employees
investor.kimberly-clark.com/email-alerts
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/kimberly-clark-sustainability-report_2016_supply-chain.pdf?la=fr-ca
www.Kimberly-Clark.com/en-us/company/supplier-link
www.kimberly-clark.com/en-ca/esg/smallest-footprint/plastics
www.Kimberly-Clark.com/de-de/company/about-us
www.softexindonesia.com/
www.Kimberly-Clark.com/en-us/company/supplier-link/standards-and-requirements/social-compliance
www.Kimberly-Clark.com/-/media/kimberly/pdf/slavery-and-human-trafficing/kimberly-clark-statement-on-modern-slavery.pdf?la=en-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-chinese-traditional.pdf?la=es-us
www.Kimberly-Clark.com/en-us/sustainability2022/socialimpact
www.kimberly-clark.com/en-us/responsibility/ethics-governance
www.kimberly-clark.com/pt-br/accessibility
www.Kimberly-Clark.com/fr-ca/company/supplier-link/supplier-portals
www.kimberly-clark.com/en-ca/trafficking-statement
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_portuguese_umbracofile.pdf?la=fr-ca
www.Kimberly-Clark.com/ru-ru/-/media/kimberly/pdf/innovation/productevol_facialtissue_umbracofile.pdf
www.Kimberly-Clark.com/pt-br/-/media/kimberly/pdf/innovation/productevol_femininepads_umbracofile.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/ncg_committee_charter-revised_11-13-13_umbracofile.pdf?la=es-us
www.linkedin.com/company/kimberly-clark?trk=hb_tab_compy_id_3439
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/apac_invoicing-requirements_country-specifics_refresh2020.pdf?la=es-us
www.Kimberly-Clark.com/investors/corporate-governance/contact-the-board
www.Kimberly-Clark.com/es-us/company/supplier-link/standards-and-requirements/supplier-requirements
www.Kleenex.de
www.kimberly-clark.com/es-us/terms-of-use
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/p2p-supplier-portal-procurement-policy.pdf?la=ru-ru
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/apac_invoicing-requirements_country-specifics_refresh2020.pdf?la=en-us
www.unicef.org/stories/novel-coronavirus-outbreak-what-parents-should-know
www.kimberly-clark.com/pt-br/esg/smallest-footprint
www.Kimberly-Clark.com/es-us/-/media/kimberly/pdf/investors/k-c-by-laws-4-29-21.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/kimberly-clark-sustainability-report_2016_supply-chain.pdf?la=pt-br
www.kimberly-clark.com/en-us/brands/adult-care
www.Kimberly-Clark.com/es-us/brands/residuals
fr.poise.com/i18n/privacy-policy.html
www.kimberly-clark.com/ru-ru/trafficking-statement
www.facebook.com/ubykotex/photos/a.381059904937/10158172018109938/?type=3&theater
www.Kimberly-Clark.com/es-us/investors/individual-investor-services
www.Kimberly-Clark.com/es-us/brands/ingredients
www.Kimberly-Clark.com/en-us/covid-19/caring-for-those-in-need/u-by-kotex-donates-1m-products
www.Kimberly-Clark.com/pt-br/company/supplier-link/receiving-payment
www.Kimberly-Clark.com/company/supplier-link/invoice-requirements
www.Kimberly-Clark.com/pt-br/brands/our-brands
www.responsiblemineralsinitiative.org/conflict-minerals-reporting-template/
www.Kimberly-Clark.com/en-ca/covid-19/caring-for-those-in-need/childcare-for-essential-workers
www.sustainability2022.com/
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2015/2015-report.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2012/2012-report---brazil-portuguese.pdf
www.Kimberly-Clark.com/brands/our-brands
www.Kimberly-Clark.com/es-us/company/supplier-link/standards-and-requirements/social-compliance/anti-trust-compliance
news.kimberly-clark.com
www.Kimberly-Clark.com/es-us/-/media/kimberly/pdf/innovation/productevol_toilettissue_umbracofile.pdf
www.careersatkc.com/en
www.kimberly-clark.com/en-ca/company/supplier-link/responsible-supply-chain
www.Kimberly-Clark.com/es-us/-/media/kimberly/pdf/investors/compliantprocedures_umbracofile.pdf
www.Kimberly-Clark.com/ru-ru/company/supplier-link/procure-to-pay-portal
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/k-c-supplier-code-of-conduct-_english-and-spanish.pdf?la=es-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_english_umbracofile.pdf?la=en-us
www.Kimberly-Clark.com/es-us/-/media/kimberly/pdf/audit-committee-charter.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/k-c-by-laws-4-29-21.pdf?la=ru-ru
www.kimberly-clark.com/es-us/company/employees
www.kimberly-clark.com/es-us/donotsellmyinfo
www.kimberly-clark.com/ru-ru/news/news-room
www.kimberly-clark.com/en-us/accessibility
www.Kimberly-Clark.com/en-us/brands/family-care
www.kimberly-clark.com/en-us/news/news-room
www.Kimberly-Clark.com/en/responsibility/annualreports
www.Kimberly-Clark.com/pt-br/esg/policies/antitrust-and-competition-compliance
www.Kimberly-Clark.com/en-us/company/supplier-link/standards-and-requirements/animal-testing
www.Kimberly-Clark.com/fr-ca/company/supplier-link/standards-and-requirements/social-compliance/supply-chain-act
qa1.global.kimberly-clark.com/fr/investors/corporate-governance/code-of-conduct
www.w3.org/TR/WAI-WEBCONTENT/
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2012/2012-report---australia--new-zealand.pdf
www.Kimberly-Clark.com/fr-ca/company/supplier-link/standards-and-requirements/supplier-requirements
www.Kimberly-Clark.com/-/media/kimberly/pdf/eu-terms/pl-tsandcs-0810.pdf?la=en-us
www.cosmeticsinfo.org/hbi/triclosan-information/
www.kimberly-clark.com/pt-br/esg/smallest-footprint/forests
www.Kimberly-Clark.com/covid-19
www.Kimberly-Clark.com/en-us/company/supplier-link/standards-and-requirements/fiber-procurement
www.Kimberly-Clark.com/es-us/investors/corporate-governance/hedging-and-pledging-policy
www.kimberly-clark.com/es-us/brands/fragrances
www.Kimberly-Clark.com/brands/ingredients
www.Kimberly-Clark.com/fr-ca/company/supplier-link/invoice-requirements
www.Kimberly-Clark.com/fr-ca/-/media/kimberly/pdf/audit-committee-charter.pdf
www.depend.com/e
7511
n-us/privacy-policy
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-french.pdf?la=ru-ru
www.kimberly-clark.com/en-za/contact-us
www.kimberly-clark.com/ru-ru/responsibility/kc-foundation
www.ubykotex.com
www.kimberly-clark.com/es-us/esg/2030-goals
www.kimberly-clark.com/en-us/brands/family-care
www.Kimberly-Clark.com/-/media/kimberly/pdf/annual-report/2007-annual-report_umbracofile.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2018/k-c2018globalsustainabilityreportnew.pdf
www.kimberly-clark.com/pt-br/brands/our-brands
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/mdc-committee-charter.pdf?la=es-us
www.kimberly-clark.com/en-us/company/about-us
www.kimberly-clark.com/en-ca/brands/fragrances
www.Kimberly-Clark.com/en-us/company/supplier-link/standards-and-requirements/supplier-requirements/anti-corruption-compliance
www.Kimberly-Clark.com/en-us/company/supplier-link/purchase-orders
www.Kimberly-Clark.com/pt-br/brands/preservatives
www.Kimberly-Clark.com/pt/esg/2030-ambition
www.careers.kimberly-clark.com/en/our-culture
www.Kimberly-Clark.com/pt-br/responsibility/diversity-and-inclusion
www.ubykotex.com/fr-ca/privacy/
www.Kimberly-Clark.com/-/media/kimberly/pdf/ethics-and-governance/product-safety-policies.pdf?la=en-us
www.Kimberly-Clark.com/pt-br/company/supplier-link/standards-and-requirements/social-compliance
www.fda.gov/consumers/consumer-updates/5-things-know-about-triclosan
kcc-rcp.etq.com/RCPProd/reliance
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/emea_invoicing-requirements_refresh2020.pdf?la=es-us
kimberlyclark.gcs-web.com/static-files/ca3d6dd8-4548-4758-bc92-cb534546ca93
www.kimberly-clark.com/fr-ca/responsibility/annualreports
www.kimberly-clark.com/es-us/company/supplier-link/supplier-diversity
www.Kimberly-Clark.com/company/supplier-link/standards-and-requirements/social-compliance
www.kimberly-clark.com/ru-ru/company/about-us
www.Kimberly-Clark.com/es-us/investors/corporate-governance/contact-the-board
www.viveplenitud.com
www.kimberly-clark.com/es-us/company/supplier-link/supplier-portals
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2008/2008-report.pdf
www.kimberly-clark.com/en-us/company/supplier-link/responsible-supply-chain
www.Kimberly-Clark.com/fr-ca/company/supplier-link/responsible-supply-chain
www.kimberly-clark.com/es-us/brands/kc-professional
www.cottonelle.com
www.kimberly-clark.com/ru-ru/terms-of-use
www.kimberly-clark.com/en/responsibility/annualreports
www.huggies.com/en-ca/privacy-policy
www.Kimberly-Clark.com/es-us/brands/safety-commitment
www.drynites.ch
www.Kimberly-Clark.com/fr-ca/brands/fragrances
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/north-america-region--specific--payment-receipt-info.pdf?la=pt-br
www.Kimberly-Clark.com/pt-br/company/supplier-link/standards-and-requirements/supplier-requirements/anti-corruption-compliance
www.Kimberly-Clark.com/en-us/-/media/kimberly/pdf/investors/kmb-2020-government-relations-disclosure.pdf
www.Kimberly-Clark.com/investors/corporate-governance/hedging-and-pledging-policy
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2006/2006-report.pdf
www.Kimberly-Clark.com/ru-ru/company/supplier-link/responsible-supply-chain
investor.kimberly-clark.com/stock-information
csr.yuhan-kimberly.co.kr/resources_2020/file/yk_2018_en.pdf
www.Kimberly-Clark.com/fr-ca/-/media/kimberly/pdf/investors/k-c-certificate-of-incorporation-4-29-21.pdf
www.kcprofessional.es/marcas/kleenguard
www.Kimberly-Clark.com/ru-ru/-/media/kimberly/pdf/audit-committee-charter.pdf
www.kimberly-clark.com/en-nz/
www.Kimberly-Clark.com/pt-br/investors/corporate-governance/hedging-and-pledging-policy
www.Kimberly-Clark.com/pt-br/company/supplier-link/stan
www.Kimberly-Clark.com/covid-19/caring-for-our-people
www.kimberly-clark.com/en-us/brands/kc-professional
www.Huggieswindeln.de
www.Kimberly-Clark.com/company/supplier-link/supplier-diversity
www.Kimberly-Clark.com/404.aspx?item=web%3a%7bF15ED695-05BB-4CBA-AAE3-FD20294AD051%7d%40pt-BR
www.kimberly-clark.com/fr-ca/esg/smallest-footprint/forests
www.kimberly-clark.com/en-ca/company/about-us
www.Kimberly-Clark.com/es-us/company/supplier-link/supplier-diversity
www.Kimberly-Clark.com/fr-ca/sustainability2022/energyclimate
www.Kimberly-Clark.com/pt-br/company/supplier-link/invoicing
www.Kimberly-Clark.com/es-us/company/supplier-link/purchase-orders
www.Kimberly-Clark.com/-/media/kimberly/pdf/annual-report/2011_annualreport_umbracofile.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/kmb-2020-government-relations-disclosure.pdf?la=ru-ru
www.Kimberly-Clark.com/company/supplier-link/standards-and-requirements/stewardship
www.kimberly-clark.com/en-us/privacypolicy
www.Kimberly-Clark.com/-/media/kimberly/pdf/ingredients/st-14665-kimberly-clark-restricted-substances-list_june-2020.pdf?la=fr
www.sustainability2022.com/en/five-priorities/waste-and-recycling
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-italian.pdf?la=pt-br
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2006/2006-executive-summary.pdf
www.Kimberly-Clark.com/fr-ca/company/about-us
www.kimberly-clark.com/pt-br/sitemap
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/k-c-supplier-code-of-conduct-_english-and-spanish.pdf?la=en-us
www.Kimberly-Clark.com/en-us/sustainability2022/wasterecycling
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/emea_invoicing-requirements_refresh2020.pdf?la=pt-br
www.kimberly-clark.com/en-us/locations
www.Kimberly-Clark.com/ru-ru/company/leadership
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_russian_umbracofile.pdf?la=pt-br
www.kimberly-clark.com/fr-ca/PrivacyPolicy
www.Kimberly-Clark.com/fr-ca/esg/policies/antitrust-and-competition-compliance
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-italian.pdf?la=ru-ru
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/emea_invoicing-requirements_refresh2020.pdf?la=ru-ru
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/na_invoicing-requirements_refresh2020.pdf?la=ru-ru
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/kimberly-clark-sustainability-report_2016_forest-and-fiber.pdf?la=fr-ca
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_traditional-chinese_umbracofile.pdf?la=es-us
www.Kimberly-Clark.com/en-us/terms-and-conditions-en-ca
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/na_invoicing-requirements_refresh2020.pdf?la=fr-ca
www.Kimberly-Clark.com/fr-ca/-/media/kimberly/pdf/innovation/productevol_papertowel_umbracofile.pdf
www.viveplenitud.com.ar
www.Kimberly-Clark.com/pt-br/company/supplier-link/procure-to-pay
www.Kimberly-Clark.com/es-us/company/supplier-link/responsible-supply-chain
www.kimberly-clark.com/en-ca/brands/safety-commitment
www.Kimberly-Clark.com/en-us/company/supplier-link/standards-and-requirements/restricted-substances
www.Kimberly-Clark.com/pt-br/company/supplier-link/standards-and-requirements
www.Kimberly-Clark.com/es-es/investors/investor-contacts
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/guidelines_hiringemployeesofauditors_umbracofile.pdf?la=ru-ru
www.Kimberly-Clark.com/pt-br/-/media/kimberly/pdf/investors/k-c-certificate-of-incorporation-4-29-21.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_simplified-chinese_umbracofile.pdf?la=es-us
investor.kimberly-clark.com/news-releases/news-release-details/scottr-brand-teams-boys-girls-clubs-america-provide-childcare
www.kimberly-clark.com.mx/ 
www.Kimberly-Clark.com/fr-ca/company/supplier-link/standards-and-requirements/animal-testing
www.kimberly-clark.com/pt-br/esg/smallest-footprint/climate
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/apac_invoicing-requirements_country-specifics_refresh2020.pdf?la=fr-ca
www.kimberly-clark.com/en-ca/responsibility/ethics-governance
www.Kimberly-Clark.com/en-us/company/supplier-link/invoice-requirements
www.Kimberly-Clark.com/en-us/sustainability2022/energyclimate
www.drynites.fr/
www.kimberly-clark.com/es-us/responsibility/social-compliance
www.kimberly-clark.com/ru-ru/esg/social-impact
www.kimberly-clark.com/ru-ru/esg/smallest-footprint/water
investor.kimberly-clark.com/news-releases/news-release-details/west-virginia-nonprofit-and-its-partnership-rightcycle-program
www.Kimberly-Clark.com/ru/esg/social-impact
www.Kimberly-Clark.com/pt/responsibility/annualreports
www.Kimberly-Clark.com/es-us/company/supplier-link/standards-and-requirements/social-compliance/supply-chain-act
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-french.pdf?la=fr-ca
www.kclatamcarreras.com/home.aspx 
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_simplified-chinese_umbracofile.pdf?la=fr-ca
www.kimberly-clark.com/es-us/company/leadership
www.Kimberly-Clark.com/en-us/-/media/kimberly/pdf/investors/k-c-by-laws-4-29-21.pdf
www.Kimberly-Clark.com/fr-ca/-/media/kimberly/pdf/investors/mdc-committee-charter.pdf
www.kimberly-clark.com/es-us/company/supplier-link/procure-to-pay
www.Kimberly-Clark.com/es-us/company/supplier-link/risk-management
investor.kimberly-clark.com/
www.scottonelle.com/
www.intimus.com.br/
www.kimberly-clark.com/fr-ca/responsibility/sustainability2022
www.Kimberly-Clark.com/en/esg/2030-ambition
www.kimberly-clark.com/en/responsibility/kc-foundation
www.Kimberly-Clark.com/ru-ru/-/media/kimberly/pdf/innovation/productevol_disposablediaper_umbracofile.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2020/k-c-2020-global-sustainability-report-social-impact.pdf
www.kimberly-clark.com/en-us/esg/smallest-footprint/plastics
www.Kimberly-Clark.com/fr-ca/company/supplier-link/standards-and-requirements/fiber-procurement
www.3blmedia.com/News/Kimberly-Clark-Guatemala-Benefitting-Solar-Power-Switch
www.kimberly-clark.com/es-us/brands/adult-care
www.kimberly-clark.com/ru-ru/brands/our-brands
www.Kimberly-Clark.com/es/responsibility/annualreports
www.kimberly-clark.com/en-ca/esg/2030-ambition
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-indonesian.pdf?la=fr-ca
www.drynites.es/
www.Kimberly-Clark.com/en-us/company/supplier-link/supplier-diversity
www.Kimberly-Clark.com/-/media/kimberly/pdf/ingredients/st-14665-kimberly-clark-restricted-substances-list_june-2020.pdf?la=es-us
www.Kimberly-Clark.com/fr/brands/our-brands
www.Kimberly-Clark.com/en-us/-/media/kimberly/pdf/audit-committee-charter.pdf
www.kimberly-clark.com/ru-ru/esg/smallest-footprint/plastics
www.Kimberly-Clark.com/en-us/-/media/kimberly/pdf/investors/ncg-committee-charter---revised-11-19-20.pdf
www.Kimberly-Clark.com/en-us/company/supplier-link/responsible-supply-chain
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/ncg_committee_charter-revised_11-13-13_umbracofile.pdf?la=fr-ca
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/kc-codeofconduct-en.pdf?la=pt-br
www.careers.kimberly-clark.com/en/switzerland
www.Kimberly-Clark.com/fr-ca/company/unsolicited-ideas
www.Kimberly-Clark.com/
www.Kimberly-Clark.com/fr-fr/company/about-us
www.kimberly-clark.com/es-us/esg/smallest-footprint/forests
www.allianceforperiodsupplies.org/
www.Kimberly-Clark.com/ru-ru/esg/2030-ambition
www.Kimberly-Clark.com/en-us/-/media/kimberly/pdf/investors/kimberly-clark-corporate-governance-policies.pdf
www.Kimberly-Clark.com/fr-ca/company/supplier-link/standards-and-requirements/supplier-requirements/anti-corruption-compliance
www.Kimberly-Clark.com/en-us/accessibility
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-spanish.pdf?la=pt-br
support.cloudflare.com/hc/en-us/categories/200275218-Getting-Started
www.Kimberly-Clark.com/company/supplier-link/standards-and-requirements/social-compliance/business-gratuities
www.vivatowels.ca/PrivacyPolicy.aspx
www.kimberly-clark.com/en-ca/brands/ingredients
www.kimberly-clark.com/es-us/esg/smallest-footprint
www.Kimberly-Clark.com/en-us/terms-and-conditions-fr-ca
www.kimberly-clark.com/es-us/responsibility/annualreports
www.Kimberly-Clark.com/ru-ru/-/media/kimberly/pdf/innovation/productevol_toilettissue_umbracofile.pdf
www.kimberly-clark.com/pt-br/responsibility/kc-foundation
www.Kimberly-Clark.com/en-us/investors/corporate-governance/contact-the-board
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-portuguese-brazil.pdf?la=pt-br
www.Kimberly-Clark.com/en-us/investors/corporate-governance/hedging-and-pledging-policy
www.kimberly-clark.com/pt-br/esg/social-impact
www.Kimberly-Clark.com/ru-ru/investors/corporate-governance/code-of-conduct
www.pull-ups.com/es-us/privacy-policy
www.kimberly-clark.com/en-ca/brands/baby-and-child-care
www.depend.com
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/template-d--product-safety-regulatory-3party-ndarev-11252019-anthesis.docx?la=es-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/kimberly-clark-corporate-governance-policies.pdf?la=ru-ru
www.careers.kimberly-clark.com/en/italy
www.Kimberly-Clark.com/ru-ru/company/supplier-link/supplier-collaboration
www.Kimberly-Clark.com/-/media/kimberly/pdf/annual-report/2010_annualreport_umbracofile.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/lao-invoicing-requirements-country-specific_engspan-_refresh2020.pdf?la=en-us
www.Kimberly-Clark.com/fr-ca/investors/corporate-governance/code-of-conduct
www.Kimberly-Clark.com/ru-ru/investors/corporate-governance/hedging-and-pledging-policy
www.Kimberly-Clark.com/company/supplier-link/supplier-portals
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-czech.pdf?la=fr-ca
www.kimberly-clark.com.vn/en/ 
www.kimberly-clark.com/es-us/brands/our-brands
www.sustainability2022.com/five-priorities/forest-and-fiber
www.Kimberly-Clark.com/pt-br/aviso-recall
www.newswire.ca/news-releases/cottonelle-r-and-kleenex-r-brands-ask-canadians-to-shareasquarecanada-and-commit-100-000-to-united-way-centraide-canada-s-covid-19-community-response-and-recovery-fund-899655810.html
privacyportal-de.onetrust.com/webform/99096bff-8366-4b94-a7e2-97f3efa52243/06ee8bd6-6a56-4022-9b8a-9d64602904d8
www.Kimberly-Clark.com/ru-ru/brands/preservatives
www.kimberly-clark.com/en-us/company/supplier-link
www.Kimberly-Clark.com/fr-ca/responsibility/sustainability2022
www.kimberly-clark.com/fr-ca/accessibility
www.Kimberly-Clark.com/es-es/investors/corporate-governance
www.Kimberly-Clark.com/en-us
www.kimberly-clark.com/ru-ru/esg/2030-goals
www.Kimberly-Clark.com/es-us/company/innovation
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-korean.pdf?la=es-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-dutch.pdf?la=ru-ru
www.planusa.org/kotex
www.Kimberly-Clark.com/es-us/esg/social-impact
www.huggies-lingettes.fr/
www.ubykotex.com/en-ca/privacy/
www.kimberly-clark.com/en-ca/PrivacyPolicy
www.Kimberly-Clark.com/pt-br/brands/safety-commitment
www.Kimberly-Clark.com/es-us/company/supplier-link/standards-and-requirements/stewardship
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-arabic.pdf?la=pt-br
kimberlyclark.gcs-web.com/static-files/029c0249-a08d-498a-808b-9452f12eb02f
w
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/guidelines_hiringemployeesofauditors_umbracofile.pdf?la=fr-ca
www.kleenex.com/en-us/
www.Kimberly-Clark.com/es-us/sustainability2022/supplychain
www.kimberly-clark.com/ru-ru/PrivacyPolicy
qa1.global.kimberly-clark.com/-/media/kimberly/pdf/kotex-she-can-initiative/kotex_myfirstperiod.pdf?la=en
www.Kimberly-Clark.com/pt-br/brands/ingredients
www.kimberly-clark.com/fr-ca/esg/smallest-footprint/climate
qa1.global.kimberly-clark.com/-/media/kimberly/pdf/kotex-she-can-initiative/kotex_puberty.pdf?la=en
www.kimberly-clark.com/pt-br/trafficking-statement
kimberlyclark.gcs-web.com/news-releases/news-release-details/u-kotexr-addresses-need-period-products-serves-founding-sponsor
www.kimberly-clark.com/fr-ca/responsibility/social-compliance
www.kimberly-clark.com/en-ca/brands/kc-professional
www.Kimberly-Clark.com/pt-br/company/supplier-link/procure-to-pay-portal
www.Kimberly-Clark.com/en-us/eu-terms-and-conditions
www.kimberly-clark.com/en-ca/news/news-room
www.kcprofessional.ch
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/kimberly-clark-corporate-governance-policies.pdf?la=fr-ca
www.kimberly-clark.com/fr-ca/news/news-room
www.Kimberly-Clark.com/pt-br/company/supplier-link/standards-and-requirements/supplier-requirements
www.Kimberly-Clark.com/en-us/brands/residuals
nationaldiaperbanknetwork.org/
www.kcprofessional.co.za
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/kmb-2020-government-relations-disclosure.pdf?la=pt-br
www.babysoft.co.za
www.kimberly-clark.com/es-us/news/news-room
www.goodnites.com/en-ca/privacy
www.kimberly-clark.com/en-us/esg/strategy
www.Kimberly-Clark.com/fr-ca/investors/investor-contacts
www.kimberly-clark.com/en-us/ourprivacyvalues
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-russian.pdf?la=ru-ru
www.Kimberly-Clark.com/-/media/kimberly/pdf/2020-eeo-1-report.pdf
www.Kimberly-Clark.com/brands/baby-and-child-care
www.Kimberly-Clark.com/fr-ca/company/supplier-link
www.Kimberly-Clark.com/de-ch/switzerland
www.Kimberly-Clark.com/en-us/brands/baby-and-child-care
www.Kimberly-Clark.com/-/media/kimberly/pdf/ethics-and-governance/fiberprocurementpolicy.pdf?la=en-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-hebrew.pdf?la=fr-ca
www.Kimberly-Clark.com/es-us/company/supplier-link/standards-and-requirements/animal-testing
www.goodnites.com/en-us/privacy
www.Kimberly-Clark.com/en-us/esg/social-impact
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-russian.pdf?la=pt-br
www.kimberly-clark.com/en-us/brands/not-in-our-products
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/p2p-supplier-portal-procurement-policy.pdf?la=fr-ca
www.Kimberly-Clark.com/it-it/company/about-us
www.facebook.com/KimberlyClarkCorp/photos/a.158207217564030/3019005484817508/
www.Kimberly-Clark.com/fr-ca/company/supplier-link/standards-and-requirements/social-compliance/business-gratuities
www.Kimberly-Clark.com/pt/esg/social-impact
fr.ca.depend.com/i18n/privacy.html
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/na_invoicing-requirements_refresh2020.pdf?la=es-us
www.kimberly-clark.com/en-us/company/supplier-link/supplier-collaboration
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-dutch.pdf?la=en-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_korean_umbracofile.pdf?la=fr-ca
www.Kimberly-Clark.com/en-ca/
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/p2p-supplier-portal-procurement-policy.pdf?la=es-us
www.Kimberly-Clark.com/ru-ru/-/media/kimberly/pdf/investors/k-c-by-laws-4-29-21.pdf
www.unitedway.org/recovery/covid19
www.Kimberly-Clark.com/es-us/-/media/kimberly/pdf/investors/mdc-committee-charter.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/annual-report/2012_annualreport_umbracofile.pdf
www.Kimberly-Clark.com/ru-ru/responsibility/diversity-and-inclusion
www.huggies.fr/
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-thai.pdf?la=pt-br
www.Kimberly-Clark.com/esg/smallest-footprint
www.Kimberly-Clark.com/ru-ru/company/supplier-link/purchase-orders
www.kcprofessional.es/marcas/kimtech
www.Kimberly-Clark.com/ru-ru/brands/residuals
www.kimberly-clark.com/es-us/company/about-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/ncg-committee-charter---revised-11-19-20.pdf?la=pt-br
www.huggies.com/fr-ca/privacy-policy
www.Kimberly-Clark.com/ru-ru/company/about-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-vietnamese.pdf?la=ru-ru
www.Kimberly-Clark.com/-/media/kimberly/pdf/eu-terms/fr-tsandcs-0810.pdf?la=en-us
www.Kimberly-Clark.com/en-us/esg/policies/anti-corruption-compliance
www.kimberly-clark.com/es-us/sitemap
www.Kimberly-Clark.com/en-us/company/supplier-link/procure-to-
www.kleenex.fr/
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_korean_umbracofile.pdf?la=es-us
www.careers.kimberly-clark.com/en/germany
www.Kimberly-Clark.com/fr-ca/company/supplier-link/risk-management
www.kimberly-clark.com/fr-ca/esg/2030-ambition
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_malay_umbracofile.pdf?la=fr-ca
www.Kimberly-Clark.com/en-us/covid-19/caring-for-those-in-need/virtual-nicu-support-groups
www.kcprofessional.es/marcas/scott
www.kimberly-clark.com/en-ca/donotsellmyinfo
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_russian_umbracofile.pdf?la=fr-ca
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/kimberly-clark-corporate-governance-policies.pdf?la=pt-br
www.Kimberly-Clark.com/en-us/-/media/kimberly/pdf/investors/k-c-certificate-of-incorporation-4-29-21.pdf
www.Kimberly-Clark.com/terms-and-conditions-en-ca
www.ifraorg.org/en-us/ingredients
www.facebook.com/KimberlyClarkCorp
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/na_invoicing-requirements_refresh2020.pdf?la=en-us
www.kimberly-clark.com/en-ca/company/our-vision
www.Kimberly-Clark.com/-/media/kimberly/pdf/annual-report/2017_annualreport_umbracofile.pdf
www.youtube.com/watch?v=Ku9XK3el9Os
www.kimberly-clark.com/en-us/esg/smallest-footprint/climate
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-indonesian.pdf?la=en-us
www.Kimberly-Clark.com/ru-ru/-/media/kimberly/pdf/investors/k-c-certificate-of-incorporation-4-29-21.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-dutch.pdf?la=es-us
www.Kimberly-Clark.com/en-us/covid-19/caring-for-those-in-need/huggies-covid-19-relief-efforts
www.Kimberly-Clark.com/en-us/company/supplier-link/standards-and-requirements
csr.yuhan-kimberly.co.kr/resources_2020/file/yk_2014_en.pdf
www.kimberly-clark.com/es-us/company/supplier-link/responsible-supply-chain
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-dutch.pdf?la=pt-br
www.kimberly-clark.com/pt-br/news/news-room
www.Kimberly-Clark.com/~/media/kimberly/forms/SaaSTC.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/southafrica/kcsa-privacy-policy-rev2_20210909.pdf
www.kimberly-clark.com/en-us/responsibility/annualreports
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/k-c-supplier-code-of-conduct-_english-and-spanish.pdf?la=fr-ca
www.Kimberly-Clark.com/fr-ca/esg/policies/anti-corruption-compliance
www.kcprofessional.com/en-us/how-to-buy
www.kimberly-clark.com/pt-br/responsibility/social-compliance
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-portuguese-brazil.pdf?la=es-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-chinese-traditional.pdf?la=en-us
www.Kimberly-Clark.com/fr-ca/company/supplier-link/standards-and-requirements/restricted-substances
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/kmb-2020-government-relations-disclosure.pdf?la=fr-ca
www.Kimberly-Clark.com/-/media/kimberly/pdf/eu-terms/hu-tsandcs.pdf?la=en-us
www.sustainability2022.com/strategy
www.Kimberly-Clark.com/pt-br/company/patents
www.kimberly-clark.com/es-us/company/supplier-link/standards-and-requirements
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/na-supplier-requirements-list.pdf?la=fr-ca
www.Kimberly-Clark.com/company/supplier-link/responsible-supply-chain
www.Kimberly-Clark.com/en-us/company/supplier-link/standards-and-requirements/social-compliance/business-gratuities
www.Kimberly-Clark.com/en-us/-/media/kimberly/pdf/investors/guidelines_hiringemployeesofauditors_umbracofile.pdf
www.kimberly-clark.com/es-us/brands/safety-commitment
www.kimberly-clark.com/fr-ca/donotsellmyinfo
www.littleswimmers.es/
www.Kimberly-Clark.com/es-us/company/patents
www.Kimberly-Clark.com/pt-br/-/media/kimberly/pdf/innovation/productevol_disposabletrainingpants_umbracofile.pdf
www.kimberly-clark.com/en-us/esg
qa1.global.kimberly-clark.com/es/investors/corporate-governance/code-of-conduct
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/k-c-certificate-of-incorporation-4-29-21.pdf?la=es-us
www.kimberly-clark.com.br/ 
www.Kimberly-Clark.com/pt-br/-/media/kimberly/pdf/investors/ncg-committee-charter---revised-11-19-20.pdf
www.kimberly-clark.com/en-us/brands/preservatives
www.3blmedia.com/news/father-son-hakim-savoy-carries-his-dads-legacy-fighting-injustice
www.Kimberly-Clark.com/-/media/kimberly/pdf/esg/2030-ambition/goals-and-aspirations/kimberly-clark-2019-memberships.pdf
www.ifrc.org/en/who-we-are/
www.Kimberly-Clark.com/pt-br/company/supplier-link/supplier-portals
www.Kimberly-Clark.com/it-it/italy
www.kimberly-clark.com/en-us/company/technology-licensing
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2009/2009-executive-summary.pdf
kimberlyclark.gcs-web.com/rss-news-feeds
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/compliantprocedures_umbracofile.pdf?la=ru-ru
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/north-america-region--specific--payment-receipt-info.pdf?la=en-us
www.kimberly-clark.com/en-us/trafficking-statement
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2020/k-c-2020-global-sustainability-report---addendum.pdf
www.Kimberly-Clark.com/brands/ingredients/ingredient-library
www.kimberly-clark.com/en-us/company/innovation
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2013/2013-report---peru.pdf
www.Kimberly-Clark.com/en-us/esg/strategy
www.kimberly-clark.com/fr-ca/responsibility/social-impact/kotex-she-can-initiative
www.kimberly-clark.com/en-ca/brands/residuals
www.Kimberly-Clark.com/covid-19/caring-for-those-in-need
www.kimberly-clark.com/es-us/brands/not-in-our-products
www.ubykotex.com/en-us/recallfaq
www.pull-ups.com/en-us/privacy-policy
www.kimberly-clark.com/pt-br/contact-us
www.3blmedia.com/News/Kimberly-Clark-Marks-World-Oceans-Day-Joining-WWFs-ReSource-Plastic-Team
www.Kimberly-Clark.com/fr-ca
www.Kimberly-Clark.com/-/media/kimberly/pdf/esg/making-lives-better/social-impact/kimberly-clark-2020-ambitions-socialimpact.pdf?la=en-us
www.hakle.ch
www.kimberly-clark.com/ru-ru/responsibility/social-impact/kotex-she-can-initiative
www.depend.com/en-us/privacy-policy
www.Kimberly-Clark.com/cdn-cgi/l/email-protection
www.kimberly-clark.com/es-us/responsibility/social-impact/kotex-she-can-initiative
www.kimberly-clark.com/en-us/investors/annual-reports
www.kimberly-clark.com/fr-ca/company/about-us
www.Kimberly-Clark.com/es-us/responsibility/diversity-and-inclusion
www.Kimberly-Clark.com/es-us/-/media/kimberly/pdf/investors/k-c-certificate-of-incorporation-4-29-21.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/na_invoicing-requirements_refresh2020.pdf?la=pt-br
www.Kimberly-Clark.com/en-us/brands/kc-professional
www.kimberly-clark.com/es-us/company/innovation
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_thai_umbracofile.pdf?la=fr-ca
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_portuguese_umbracofile.pdf?la=es-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/ingredients/st-14665-kimberly-clark-restricted-substances-l
8000
ist_june-2020.pdf?la=fr
www.scottbrand.com/en-us/
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/kimberly-clark-corporate-governance-policies.pdf?la=es-us
www.Kimberly-Clark.com/ru-ru/-/media/kimberly/pdf/investors/ncg-committee-charter---revised-11-19-20.pdf
www.kimberly-clark.com/pt-br/esg/smallest-footprint/plastics
www.kimberly-clark.com/fr-ca/ourprivacyvalues
www.kimberly-clark.com/es-us/esg/smallest-footprint/water
www.Kimberly-Clark.com/ru-ru/brands/baby-and-child-care
www.Kimberly-Clark.com/-/media/kimberly/pdf/southafrica/paia-manual-kimberly--clark-of-south-africa_rev3_06-sep-2021.pdf
www.Kimberly-Clark.com/es-us/esg/policies/antitrust-and-competition-compliance
www.Kimberly-Clark.com/fr-ca/investors/individual-investor-services
www.Kimberly-Clark.com/en-us/company/leadership
www.Kimberly-Clark.com/es-us/company/technology-licensing
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-spanish.pdf?la=ru-ru
www.kimberly-clark.com/en-ca/accessibility
www.Kimberly-Clark.com/fr-ca/company/supplier-link/standards-and-requirements/social-compliance/anti-trust-compliance
www.Kimberly-Clark.com/pt-br/-/media/kimberly/pdf/investors/mdc-committee-charter.pdf
www.UbyKotex.com
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2015/2015-report---argentina.pdf
www.kimberly-clark.com/ru-ru/responsibility/social-compliance
www.Kimberly-Clark.com/es-us/esg/2030-ambition
www.Kimberly-Clark.com/fr/responsibility/annualreports
www.computershare.com
www.Kimberly-Clark.com/es-us/company/supplier-link/invoice-requirements
www.kimberly-clark.com/en-us/company/supplier-link/supplier-diversity
www.kimberly-clark.com/en-ca/responsibility/social-impact/kotex-she-can-initiative
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-spanish.pdf?la=fr-ca
www.kimberly-clark.com/en-us/responsibility/social-compliance
www.kimberly-clark.com/en-ca/brands/not-in-our-products
www.kimberly-clark.com/en-us/brands/baby-and-child-care
www.Kimberly-Clark.com/~/media/kimberly/forms/KCMSCA.pdf
www.kimberly-clark.com/en/
www.Kimberly-Clark.com/fr-ca/investors/corporate-governance
www.kimberly-clark.com/en/investors/corporate-governance/code-of-conduct
www.Kimberly-Clark.com/fr-ca/brands/feminine-care
www.Kimberly-Clark.com/es-us/company/supplier-link/standards-and-requirements/quality
www.Kimberly-Clark.com/ru-ru/-/media/kimberly/pdf/investors/guidelines_hiringemployeesofauditors_umbracofile.pdf
www.Kimberly-Clark.com/fr-ca/brands/family-care
www.Kimberly-Clark.com/en-us/covid-19/caring-for-our-people
www.Kimberly-Clark.com/pt-br/esg/policies/anti-corruption-compliance
www.Kimberly-Clark.com/pt-br/investors/annual-reports
www.Kimberly-Clark.com/es-us/brands/kc-professional
www.Kimberly-Clark.com/en-za/southafrica
www.Kimberly-Clark.com/pt-br/company/employees
www.kimberly-clark.com/en-ca/contact-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/kimberly-clark-sustainability-report_2016_supply-chain.pdf?la=es-us
www.kimberly-clark.com/en-us/company/patents
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/template-d--product-safety-regulatory-3party-ndarev-11252019-anthesis.docx?la=e
8000
n-us
www.kimberly-clark.com/en-ca/esg/social-impact
www.Kimberly-Clark.com/-/media/kimberly/pdf/audit-committee-charter.pdf?la=pt-br
www.Kimberly-Clark.com/en-us/investors/corporate-governance/con
www.kimberly-clark.co.il/ 
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2019/kc-2019-sustainability-report-addendum.pdf
www.Kimberly-Clark.com/en-us/locations/india
www.Kimberly-Clark.com/fr-ca/company/supplier-link/standards-and-requirements/quality
www.Kimberly-Clark.com/pt-br/brands/residuals
www.Kimberly-Clark.com/ru-ru/-/media/kimberly/pdf/investors/kimberly-clark-corporate-governance-policies.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-czech.pdf?la=es-us
www.news.kimberly-clark.com/awards
www.Kimberly-Clark.com/pt-br/-/media/kimberly/pdf/innovation/productevol_toilettissue_umbracofile.pdf
www.Kimberly-Clark.com/en-us/brands/preservatives
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-turkish.pdf?la=es-us
www.kimberly-clark.com/en-ca/company/supplier-link/supplier-collaboration
www.cosmeticsinfo.org/hbi/paraben-information/
www.kimberly-clark.com/en-us/trafficking-s
www.Kimberly-Clark.com/fr-ca/company/supplier-link/standards-and-requirements
www.Kimberly-Clark.com/es-us/company/supplier-link/invoicing
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-turkish.pdf?la=ru-ru
www.Kimberly-Clark.com/fr-ca/brands/baby-and-child-care
www.huggies.it/
www.Kimberly-Clark.com/ru-ru/brands/not-in-our-products
www.kimberly-clark.com/en-us/contact-us
www.sustainability2022.com/our-stories/goes-the-smartway
www.Kimberly-Clark.com/pt-br/brands/adult-care
www.Kimberly-Clark.com/pt-br/brands/family-care
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-french.pdf?la=en-us
www.Kimberly-Clark.com/es-us/company/supplier-link/standards-and-requirements/social-compliance/sustainability-policies
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/k-c-certificate-of-incorporation-4-29-21.pdf?la=ru-ru
www.Cottonelle.de
investor.kimberly-clark.com/financial/proxy-statement
www.Kimberly-Clark.com/pt-br/-/media/kimberly/pdf/innovation/productevol_papertowel_umbracofile.pdf
www.3blmedia.com/news/humanity-centric-innovation-redefining-meaning-billionaire
www.Kimberly-Clark.com/en-us/-/media/kimberly/pdf/investors/mdc-committee-charter.pdf
www.kimberly-clark.com/en-us/sitemap
www.Kimberly-Clark.com/es-us/company/supplier-link/procure-to-pay
www.Kimberly-Clark.com/brands/not-in-our-products
www.marcaneve.com.br/
www.Kimberly-Clark.com/en-us/responsibility/annualreports
www.Kimberly-Clark.com/pt-br/esg/policies/business-gratuities
www.Kimberly-Clark.com/fr-ca/investors/annual-reports
www.Kimberly-Clark.com/es-us/investors/annual-reports
www.kimberly-clark.com/fr-ca/terms-of-use
www.Kimberly-Clark.com/es-us/-/media/kimberly/pdf/investors/kimberly-clark-corporate-governance-policies.pdf
www.kimberly-clark.co.th/ 
www.Kimberly-Clark.com/pt-br/company/supplier-link/invoice-requirements
www.Kimberly-Clark.com/fr-ca/-/media/kimberly/pdf/investors/k-c-by-laws-4-29-21.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-russian.pdf?la=en-us
www.Kimberly-Clark.com/fr-ca/company/supplier-link/purchase-orders
menstrualhygieneday.org/
www.kimberly-clark.com/ru-ru/ourprivacyvalues
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2017/2017-report---australia-new-zealand.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/investors/ncg_committee_charter-revised_11-13-13_umbracofile.pdf?la=pt-br
www.Kimberly-Clark.com/en-us/covid-19/caring-for-our-consumers
csr.yuhan-kimberly.co.kr/resources_2020/file/yk_2020_en.pdf
www.kimberly-clark.com/en-ca/company/supplier-link/supplier-portals
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_traditional-chinese_umbracofile.pdf?la=pt-br
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-slovenian.pdf?la=pt-br
www.facebook.com/KimberlyClar
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-french.pdf?la=es-us
www.Drynites.de
www.kimberly-clark.com/fr-ca/esg/smallest-footprint/water
kimberlyclark.gcs-web.com/news-releases/news-release-details/kimberly-clark-receives-sbti-approval-its-expanded-science-based
www.kimberly-clark.com/en-ca/brands/preservatives
www.Kimberly-Clark.com/supplier-diversity
www.pull-ups.com/fr-ca/privacy-policy
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2013/2013-report.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2014/2014-report---mexico.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2020/k-c-2020-global-sustainability-report-carbon.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/annual-report/2013_annualreport_umbracofile.pdf
www.Kimberly-Clark.com/fr-ca/company/employees
www.kimberly-clark.com/es-us/privacypolicy
www.cloudflare.com/5xx-error-landing
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/na-supplier-requirements-list.pdf?la=en-us
www.kimberly-clark.com/en-us/brands/ingredients
www.sustainability2022.com/five-priorities/supply-chain
www.kimberly-clark.com/en-us/esg/smallest-footprint
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2012/2012-report---central-america-caribbean-spanish.pdf
www.Kimberly-Clark.com/pt-br/investors/individual-investor-services
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-italian.pdf?la=fr-ca
www.kimberly-clark.com/fr/contact-us
www.kimberly-clark.com/es-us/responsibility/kc-foundation
www.Kimberly-Clark.com/-/media/kimberly/pdf/southafrica/kcsa-website-terms-and-conditions-of-purchasegoods-and-or-servicesrev-5-06092021-003.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-indonesian.pdf?la=es-us
www.kimberly-clark.com/es-us/contact-us
www.kimberly-clark.com/en-ca/brands/our-brands
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-chinese-simplified.pdf?la=es-us
www.kimberly-clark.com/en-ca/brands/family-care
www.Kimberly-Clark.com/es-us/company/supplier-link/supplier-portals
csr.yuhan-kimberly.co.kr/resources_2020/file/yk_2015_en.pdf
www.Kimberly-Clark.com/pt-br/brands/fragrances
www.Kimberly-Clark.com/-/media/kimberly/pdf/ingredients/st-14665-kimberly-clark-restricted-substances-list_june-2020.pdf?la=ru-ru
www.Kimberly-Clark.com/ru-ru/company/supplier-link/standards-and-requirements
www.Kimberly-Clark.com/-/media/kimberly/pdf/audit-committee-charter.pdf?la=es-us
www.Kimberly-Clark.com/es-us/company/supplier-link/standards-and-requirements
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2020/k-c-2020-global-sustainability-report.pdf?la=en-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-czech.pdf?la=ru-ru
www.facebook.com/AndrexUK
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-german.pdf?la=en-us
www.Kimberly-Clark.com/en-us/-/media/kimberly/pdf/investors/compliantprocedures_umbracofile.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-slovenian.pdf?la=fr-ca
investor.kimberly-clark.com/events-and-presentations/events/?auth_token=63860fdb-8d1f-414c-85f3-5a1a1da44f19
www.3blmedia.com/news/owning-safety-mindset-and-way-life
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-vietnamese.pdf?la=en-us
www.Kimberly-Clark.com/pt-br/-/media/kimberly/pdf/innovation/productevol_facialtissue_umbracofile.pdf
www.Kimberly-Clark.com/pt-br
www.Kimberly-Clark.com/es-us/company/our-vision
www.kimberly-clark.com/pt-br/company/about-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_malay_umbracofile.pdf?la=pt-br
www.Kimberly-Clark.com/-/media/kimberly/pdf/annual-report/2015_annualreport_umbracofile.pdf
www.Kimberly-Clark.com/es-us/company/supplier-link/standards-and-requirements/restricted-substances
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-vietnamese.pdf?la=fr-ca
www.Kimberly-Clark.com/pt-br/company/supplier-link/supplier-diversity
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-slovenian.pdf?la=en-us
www.kimberly-clark.com/en-ca/company/leadership
www.kimberly-clark.com/en-us/responsibility/social-impact/toilets-change-lives
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-hebrew.pdf?la=pt-br
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_hebrew_umbracofile.pdf?la=en-us
www.Kimberly-Clark.com/404.aspx?item=web%3a%7bF15ED695-05BB-4CBA-AAE3-FD20294AD051%7d%40en-US
www.Kimberly-Clark.com/ru/esg/2030-ambition
www.kimberly-clark.com/en-ca/company/innovation
www.Kimberly-Clark.com/fr-ca/-/media/kimberly/pdf/investors/kimberly-clark-corporate-governance-policies.pdf
www.Kimberly-Clark.com/company/supplier-link/standards-and-requirements
www.Kimberly-Clark.com/en-us/company/supplier-link/supplier-collaboration
www.Kimberly-Clark.com/es-es/investors/annual-reports
www.Kimberly-Clark.com/en-ca/covid-19/caring-for-those-in-need/virtual-nicu-support-groups
www.Kimberly-Clark.com/ru-ru/company/supplier-link/supplier-portals
www.goodnites.com/fr-ca/privacy
www.Kimberly-Clark.com/en-us/esg/smallest-footprint/climate
www.kimberly-clark.com/fr-ca/responsibility/kc-foundation
www.Kimberly-Clark.com/en-us/trafficking-st
www.kimberly-clark.com/pt-br/esg/strategy
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-russian.pdf?la=fr-ca
www.Kimberly-Clark.com/ru-ru/esg/social-impact
www.Kimberly-Clark.com/-/media/kimberly/pdf/esg/2030-ambition/our-strategy/kimberly-clark-2030-strategy.pdf?la=en-us
www.andrex.co.uk
www.Kimberly-Clark.com/ru-ru/-/media/kimberly/pdf/investors/compliantprocedures_umbracofile.pdf
www.Kimberly-Clark.com/es-us/investors/investor-contacts
www.Kimberly-Clark.com/-/media/kimberly/pdf/annual-report/kmb-2016-10k_umbracofile.pdf
www.Kimberly-Clark.com/fr-ca/esg/strategy
www.Kimberly-Clark.com/es-us/investors/corporate-governance/code-of-conduct
www.Kimberly-Clark.com/es-es/spain
www.cosmeticsinfo.org/ingredients/phenoxyethanol/
www.Kimberly-Clark.com/fr-fr/france
www.Kimberly-Clark.com/en-us/company/supplier-link/standards-and-requirements/supplier-requirements
kimberlyclark.gcs-web.com/news-releases/news-release-details/kimberly-clarks-signature-sanitation-program-toilets-change
www.Kimberly-Clark.com/en-us/investors/corporate-governance/stock-option-purchases
www.kimberly-clark.com/en-ca/responsibility/kc-foundation
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2016/2016-report.pdf
www.Kimberly-Clark.com/ru-ru/brands/our-brands
www.Kimberly-Clark.com/ru-ru/company/supplier-link/procure-to-pay
www.kimberly-clark.com/fr-ca/responsibility/ethics-governance
www.Kimberly-Clark.com/en-ca/company/about-us
www.Kimberly-Clark.com/ru-ru/brands/feminine-care
login.taulia.com/login?style=Kimberly-Clark
www.Kimberly-Clark.com/en-us/company/supplier-link/procure-to-pay
www.kcprofessional.com
www.kimberly-clark.com/en-ca/terms-of-use
www.Kimberly-Clark.com/en-us/esg/policies/business-gratuities
csr.yuhan-kimberly.co.kr/resources_2020/file/yk_2011_en.pdf
www.essencialpravc.com.br/
www.Kimberly-Clark.com/pt-br/brands/baby-and-child-care
www.Kimberly-Clark.com/en-us/company/supplier-link/standards-and-requirements/safety-and-regulatory-disclosure
www.3blmedia.com/news/kimberly-clark-named-one-americas-most-just-companies-just-capital
www.Kimberly-Clark.com/esg/policies/anti-corruption-compliance
www.Kimberly-Clark.com/company/about-us
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-chinese-simplified.pdf?la=pt-br
www.kimberly-clark.com/es-us/esg/smallest-footprint/climate
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2014/2014-report---brazil.pdf
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-italian.pdf?la=es-us
www.Kimberly-Clark.com/pt-br/company/supplier-link/purchase-orders
youtu.be/6np4eAv68Iw
www.Kimberly-Clark.com/es-us/brands/not-in-our-products
www.Kimberly-Clark.com/fr-ca/brands/adult-care
www.Kimberly-Clark.com/-/media/kimberly/pdf/supplier-link/supplier-social-compliance-standards-final---2014_russian_umbracofile.pdf?la=en-us
www.Kimberly-Clark.com/es-us/company/leadership
www.Kimberly-Clark.com/es-us/investors/corporate-governance/stock-option-purchases
www.Kimberly-Clark.com/company/supplier-link/procure-to-pay
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2003/2003-report.pdf
www.Kimberly-Clark.com/404.aspx?item=web%3a%7bF15ED695-05BB-4CBA-AAE3-FD20294AD051%7d%40fr-CA
www.yuhan-kimberly.co.kr/
www.Kimberly-Clark.com/ru-ru/sustainability2022/supplychain
www.camelia.com
www.Kimberly-Clark.com/pt-br/esg/smallest-footprint
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-korean.pdf?la=pt-br
www.Kimberly-Clark.com/es-us/company/supplier-link
www.instagram.com/kccorp/
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2016/2016-report--australia--new-zealand.pdf
www.youtube.com/user/KimberlyClarkComms
www.kimberly-clark.com/en-us/brands/fragrances
www.kimberly-clark.com/es-us/company/technology-licensing
www.kleenex.com/fr-ca/privacy-policy
careers.kimberly-clark.com/our-culture
www.kimberly-clark.com/fr-ca/esg
www.Kimberly-Clark.com/fr-ca/esg/smallest-footprint
www.Kimberly-Clark.com/es-us/-/media/kimberly/pdf/investors/ncg-committee-charter---revised-11-19-20.pdf
www.Kimberly-Clark.com/ru-ru/company/supplier-link
www.Kimberly-Clark.com/contact-us
francais.cottonelle.com/privacy-policy
www.Kimberly-Clark.com/es-us/company/supplier-link/standards-and-requirements/fiber-procurement
www.Kimberly-Clark.com/-/media/kimberly/pdf/sustainability-reports/2019/kc-2019-sustainability-report.pdf
www.instagram.com/p/B9DYJpogYyl/
www.Kimberly-Clark.com/-/media/kimberly/pdf/codeofconduct/code-of-conduct-french.pdf?la=pt-br
