www.fcx.com/sites/fcx/files/documents/sustainability/audits/Executive_Summary_Audit_PTFI_2011.pdf
www.fcx.com/operations/south-america
www.fcx.com/freeport-features/200106
www.fcx.com/suppliers/vendor-requirements
www.fcx.com/freeport-features/042721
www.fcx.com/suppliers/europe
s22.q4cdn.com/529358580/files/doc_financials/proxy/FCX_Prox_2021.pdf
www.fcx.com/freeport-features/091520
www.fcx.com/freeport-features
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/071520
www.fcx.com/covid-info/061120
www.fcx.com/sites/fcx/files/documents/policies/pbc_dutch.pdf?d=20211115
www.newsweek.com/americas-most-responsible-companies-2020
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/020821
coppermark.org/
www.fcx.com/sites/fcx/files/documents/suppliers/csm_spanish.pdf
event.on24.com/wcc/r/3575340/1D270EB421FE105A75A5D9B7E16AFC50 
www.fcx.com/sites/fcx/files/documents/operations/TRS-CerroVerde.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/082321
www.fcx.com/sustainabil
5275
ity/people/impacts
www.fcx.com/sites/fcx/files/documents/policies/inclu_divers_pol_bahasa.pdf
www
243b
.freeportinmycommunity.com/
www.fcx.com/sites/fcx/files/documents/suppliers/sulfuric_acid_handling_policy.pdf
www.fcx.com/freeport-features/083121
www.fcx.com/company/policies.htm
media.ford.com/content/fordmedia/fna/us/en/news/2020/10/14/ford-first-corporate-partner-the-copper-mark.html
www.fcx.com/terms-and-conditions
www.fcx.com/freeport-features/090320
www.climaxmolybdenum.com/
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/082521
www.facebook.com/watch/?v=245772693138975&extid=wd4BCU7mHiyfzLPz
www.fcx.com/sites/fcx/files/documents/suppliers/surface_blasting_french.pdf
whc.unesco.org/
worldarchery.sport/news/173159/brady-ellison-breaks-world-record-702-point-qualification-pan-american-games
www.fcx.com/node/586
www.fcx.com/sites/fcx/files/documents/policies/pbc_bahasa.pdf?d=20211115
www.fcx.com/sites/fcx/files/documents/suppliers/1su.pdf
www.fcx.com/a
9b96
bout/board-of-directors
www.fcx.com/freeport-features/112720
d2y36twrtb17ty.cloudfront.net/sessions/e178d3eb-951a-4ae3-a3a2-ac4601221bce/0f37785d-7e40-474a-b417-ac4601221bd9-2cf36b30-094a-4972-af14-ac4601236248.mp4
www.fcx.com/covid-19/updates
sdgs.un.org/goals
www.fcx.com/sites/fcx/files/documents/policies/com_pol.pdf
www.irs.gov/pub/irs-pdf/iw8imy.pdf
kvgo.com/citi/freeport-mcmoran-2020
www.fcx.com/sustainability/people/land-use
www.freeportinmycommunity.com/communities/global-comunity-contacts  
www.fcx.com/sites/fcx/files/documents/suppliers/interaction_heavy_mobile_equipment.pdf
www.fcx.com/sites/fcx/files/images/sustainability/copper-mark/sm-table0910.svg
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/200601
www.irs.gov/Individuals/International-Taxpayers
supplier.ariba.com/
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/121721
www.fcx.com/sites/fcx/files/documents/sustainability/FCX-Sustainability-Report-2020-SASB-Index.pdf
www.fcx.com/sites/fcx/files/documents/covid/power_protection/maskup_morenci.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/audits/Findings_Matrix_Responses_Sept_2010.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/09102020
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/09242020a
www.fcx.com/freeport-features/03262020
www.fcx.com/freeport-features/012822
www.fcx.com/sustainability/environment
www.fcx.com/sites/fcx/files/documents/sustainability/2016_cdp_info_req.pdf
www.mountainyouth.org/
www.fcx.com/operations/
2c14
north-america
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/082720
www.fcx.com/freeport-features/081621
www.fcx.com/sites/fcx/files/documents/suppliers/fatigue_management_guideline.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/090321
www.fcx.com/sites/fcx/files/documents/sustainability/2015_cdp_info_req.pdf
www.fcx.com/about/history
www.fcx.com/sustainability/approach/economic-impact
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/200610
www.fcx.com/freeport-features/032621
event.on24.com/wcc/r/1824252/1D2F3ABA36330AB1E9FCE85BD53DC846
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/200331
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/04162020
www.fcx.com/sustainability/approach/policies/political-activity-documents
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/121621
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/03122020

243e
www.freeportinmycommunity.com/
www.fcx.com/node/596
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/01022020
www.fcx.com/freeport-features/102021
www.fcx.com/freeport-features/200203
www.fcx.com/sites/fcx/files/documents/sustainability/audits/FINALPTFIAuditExeSum.pdf
www.fcx.com/freeport-features/072120
www.fcx.com/freeport-features/200617
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_span_2013.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/uk_modern_slavery_act_statement_2018.pdf
www.fcx.com/sites/fcx/files/documents/policies/2020_FCX_PAC_Political_Contributions.pdf
www.fcx.com/sustainability/business
www.forbes.com/just-companies/
mythresults.com/arrow-machine-gun
www.fcx.com/
www.fcx.com/sites/fcx/files/documents/suppliers/working_at_heights_policy.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/2019-assurance-statement.pdf
olympics.com/tokyo-2020/en/
www.fcx.com/freeport-features/111021
jobs.fcx.com/South-America?locale=es_MX
www.fcx.com/sites/fcx/files/documents/sustainability
6a7d
/UK_Modern_Slavery_Act_Statement_2020.pdf
www.fcx.com/freeport-features/01142021
www.fcx.com/freeport-features/071520
www.fcx.com/suppliers/tools-for-suppliers
d2y36twrtb17ty.cloudfront.net/sessions/75e3e728-634e-44b0-9f57-abb3000098e8/7d9fbfbe-0aa7-4370-af72-abb3000098f2-4b8641d7-d229-4c2e-a8c3-abb30002d0fb.mp4
www.fcx.com/sites/fcx/files/documents/policies/Principles_Business_Conduct-english.pdf
www.fcx.com/freeport-features/010722
www.fcx.com/sustainability/people/artisanal_mining
www.fcx.com/sites/fcx/files/documents/sustainability/2014_ghg_verification_state.pdf
d2y36twrtb17ty.cloudfront.net/sessions/2d21b34a-3625-42b2-b519-ab51013c0f90/8f8a0c8a-261d-4cd1-9019-ab51013c0f99-15729360-f527-4eb8-bad5-ab51014190a5.mp4
www.fcx.com/covid-19/indonesia
www.fcx.com/suppliers/indo
www.fcx.com/freeport-features/040721
www.usasean.org/
PTFI-Underground-Development-2018.azureedge.net
www.fcx.com/sites/fcx/files/documents/policies/2014_FCX_PAC_Political_Contributions.pdf
www.fcx.com/sites/fcx/files/documents/policies/pbc_dutch.pdf?d=20211207
www.fcx.com/node/601
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/06252021
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/040921
www.fcx.com/sites/fcx/files/documents/corp_gov/corp_gov_guidelines.pdf?d=20220209
www.fcx.com/operation
57ec
s/north-america
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/02202020
www.fcx.com/sites/fcx/files/documents/policies/envi_pol_fr.pdf
www.fcx.com/freeport-features/120921
www.fcx.com/freeport-features/060421
www.fcx.com/freeport-features/12182020
www.spglobal.com/esg/csa/yearbook/2022/ranking/index.aspx?utm_medium=marketo&utm_source=email&utm_campaign=YB22incl
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_span_2018.pdf
www.fcx.com/sites/fcx/files/documents/policies/saf_health_pol_espanol.pdf
www.fcx.com/suppliers/chile
d2y36twrtb17ty.cloudfront.net/sessions/f0d34f3f-11dc-47ff-b044-ac7c0119b6bc/88b64496-220e-4e27-97af-ac7c0119b6c5-1f6151aa-764e-4414-aa8c-ac84010a93db.mp4
www.fcx.com/sites/fcx/files/documents/sustainability/vol_principle_2013.pdf
www.fcx.com/freeport-features/011322
www.fcx.com/o
8022
perations/north-america
www.fcx.com/sites/fcx/files/documents/sustainability/2020_ghg_verification_state.pdf
www.fcx.com/sites/fcx/files/documents/policies/2019_FCX_Political_Contributions.pdf
www.fcx.com/sites/fcx/files/documents/policies/2014_FCX_Political_Contributions.pdf
www.fcx.com/covid-19
www.fcx.com/suppliers/namining
www.fcx.com/suppliers/commodity-management
www.fcx.com/sites/fcx/files/documents/suppliers/csm_dutch.pdf
www.fcx.com/suppliers/overview
www.fcx.com/sites/fcx/files/documents/policies/pbc_peruvian.pdf
www.fcx.com/sites/fcx/files/documents/policies/envi_pol_espanol.pdf?d=20220110
www.fcx.com/freeport-features/04302020
www.fcx.com/node/121
www.fcx.com/sites/fcx/files/documents/fast_facts/sierrita.pdf
d2y36twrtb17ty.cloudfront.net/sessions/fecbfe8b-0ff2-4471-9040-ace0010314fb/14d5bc66-f472-4ddc-836e-ace001031504-f8b5f38b-1dcd-4c4d-84f0-ace0010f5a5a.mp4
www.fcx.com/sustainability/reports-and-documents
www.gcssfs.org/planetary-consciousness.html
www.privacyshield.gov/
www.fcx.com/sites/fcx/files/documents/policies/Anti-Corruption_Policy.pdf
login.cfis.sos.state.nm.us/
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/090920
www.fcx.com/covid-info/031021
event.on24.com/eventRegistration/EventLobbyServlet?target=reg20.jsp&referrer=https%3A%2F%2Ffcx.com%2F&eventid=2152547&sessionid=1&key=EB4F8C052C2DC4874B53A0FED675294F&regTag=&sourcepage=register
www.fcx.com/covid-info/033020
www.fcx.com/freeport-features/090321
event.on24.com/wcc/r/1772934/E6818D4E7A6C1A3D739A82094F7AC311
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/022421
www.summitdaily.com/news/invaluable-caregivers-lean-on-timberline-adult-day-services-for-comfort-community-and-care-during-pandemic/
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/010721
www.fcx.com/sites/fcx/files/documents/corp_gov/corp_gov_guidelines.pdf
fcx.com/sustainability/people
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/09032020
www.bisbeesciencelab.org/
www.irs.gov/pub/irs-pdf/fw8bene.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/2020-annual-report-on-sustainability.pdf
www.fcx.com/sites/fcx/files/documents/corp_gov/FCX-By-Laws.pdf
www.fcx.com/sites/fcx/files/documents/policies/2018_FCX_Political_Contributions.pdf
www.fcx.com/sites/fcx/files/documents/policies/2016_FCX_Political_Contributions.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_2016.pdf
desertmuseum.org/buffelgrass/learn.php
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/120921
www.fcx.com/node/556
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/011422
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/033021
www.fcx.com/freeport-features/030221
view.publitas.com/freeport-mcmoran/mining-engineering-feb-2021/page/1
www.fcx.com/sites/fcx/files/documents/policies/2018_FCX_PAC_Political_Contributions.pdf
fmi.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=fb65d384-499d-49fb-a652-ad5801883057
www.fcx.com/about/contact-the-board
www.fcx.com/freeport-features/09172021
www.fcx.com/sites/fcx/files/documents/suppliers/flagging_barricading_guideline_spanish.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/200507
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/100620
investors.fcx.com/investors/default.aspx
www.fcx.com/freeport-features/02202020
nma.org/2021/09/14/leaders-in-mine-safety-and-technology-honored-by-nma-and-niosh/
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/05122020
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_span_2011.pdf
fcx.com/sites/fcx/files/documents/policies/hr_policy_bahasa.pdf
www.fcx.com/sites/fcx/files/documents/policies/com_pol_espanol.pdf
www.fcx.com/about/board-committees
www.fcx.com/sites/fcx/files/documents/policies/anticorruption_policy_spanish.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_span_2017.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/vol_principle_2016.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/030321
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_bahasa_2014.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/audits/PWRA.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_span_2008.pdf
www.fcx.com/sites/fcx/files/documents/suppliers/standard_safety_policy.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/05062021
www.fcx.com/sustainability/people/inclusion_diversity
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/050421
costarters.co/
d2y36twrtb17ty.cloudfront.net/sessions/d51cd07f-4705-445d-b7e7-acf60187ff31/7aa923a1-fb28-486b-91a5-acf60187ff36-b825d394-8d9c-4419-8359-acf700033c3e.mp4
www.fcx.com/covid-19/south-america
www.fcx.com/freeport-features/110520
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/01162020
www.fcx.com/freeport-features/08272020
www.fcx.com/freeport-features/030321
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/062221
projects.gbreports.com/chile-mining-2021/freeport-mcmoran-interview/
urldefense.com/v3/__https:/pandemictaskforce.org/home__;!!HOnwNcP_IqU1!VsXqh-HoalZVdx9xgZD3ygSiEYb5f-NCw0u9m-9eY9gohtiP0lk_9jxBptef$
www.fcx.com/operations
www.youtube.com/watch?v=IBRz1hIaPG0&list=PL_7BYaXpr2rVJPSzHq2RTHgFR6Vg-veqm
www.fcx.com/sites/fcx/files/documents/FCX_181221.pdf
www.freeportinmycommunity.com/pages/native-american-programs
www.fcx.com/sites/fcx/files/documents/sustainability/mt_climb.pdf
www.fcx.com/sites/fcx/files/documents/suppliers/metal-fume-control.pdf
www.usarchery.org/
www.fcx.com/about/board-of-directors
www.fcx.com/covid-info/032320
www.fcx.com/sites/fcx/files/documents/sustainability/uk_modern_slavery_act_statement_2017.pdf
tracer.sos.colorado.gov/PublicSite/SearchPages/CommitteeDetail.aspx?OrgID=12331
www.fcx.com/covid-info/100220
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/011321
www.fcx.com/sites/fcx/files/documents/sustainability/program_response_water_2018.pdf
investors.fcx.com/investors/financial-information/annual-reports-and-proxy/default.aspx
www.fcx.com/covid-info/103020
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/07302021
www.fcx.com/sites/fcx/files/documents/suppliers/confined_space_policy.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_Span2012.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/100421
www.fcx.com/sites/fcx/files/documents/sustainability/2019-water-report.pdf
www.fcx.com/freeport-features/112921
www.fcx.com/sites/fcx/files/documents/covid/power_protection/power_of_protect_poster.pdf
www.fcx.com/freeport-features/01022020
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/08272020
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/061621
www.fcx.com/freeport-features/1125021
www.fcx.com/sites/fcx/files/documents/sustainability/2020-Climate-Report.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/uk_modern_slavery_act_statement_2016.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/StatementonFutureProjectsandRiverineTailings.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_fr_2014.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/audits/MontWatAudit_Rec.pdf
www.fcx.com/covid-info/041720
www.fcx.com/sustainability/environment/ptfi-external-audits
www.fcx.com/sustainability/people/embedding-respect
www.cerroverde.pe/
www.fcx.com/sites/fcx/files/documents/sustainability/2018_cdp_info_req.pdf
www.fcx.com/sustainability/communities
www.fcx.com/covid-info/020921
view.publitas.com/freeport-mcmoran/2019-annual-report-on-sustainability/page/1
www.freeportinmycommunity.com/
www.fcx.com/freeport-features/07302021
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/102821
www.fcx.com/sustainability/approach/audits_assessments
www.youtube.com/watch?v=7UCSOYrtKpY
www.fcx.com/covid-info/081820
www.fcx.com/sites/fcx/files/documents/suppliers/ew_er_electrical_safety.pdf
www.fcx.com/sustainability/environment/tailings/controlled-riverine-tailings-management
d.newsweek.com/en/file/459820/methodology-americas-most-responsible-companies.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_fr_2010.pdf
drms.colorado.gov/
www.fcx.com/freeport-features/040921
www.fcx.com/freeport-features/12242020
fcx.com/sustainability/environment
www.fcx.com/sustainability/approach/policies/political-activity-and-spending
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/02132020
www.fcx.com/covid-info/111220
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/021022
bmi.state.nm.us/
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/12182020
www.fcx.com/sites/fcx/files/documents/suppliers/PTFI_Indonesia.pdf
fcx.com/sites/fcx/files/documents/policies/anticorruption_policy_bahasa.pdf
www.fmjobs.com/
aiccusa.org/
www.fcx.com/freeport-features/081021
d2y36twrtb17ty.cloudfront.net/sessions/df42c8e2-c1ba-428d-a406-abea011436cc/d13b410a-f79f-4563-8842-abea011436e3-6f829b7f-2bba-4923-8d98-abea01310232.mp4
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/07222021
www.facebook.com/FreeportFCX/?__tn__=%2Cd%2CP-R&amp;eid=ARCm9-jnY5saqi8CIweItp7KgAxhWMhZfMhNvHAwHockhPvkUccZZxF8ITdmTJO0Ab1TIj0zGRtqUZF3
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/112720
www.fcx.com/sustainability/people/public-health
www.fcx.com/sites/fcx/files/documents/policies/saf_health_pol_bahasa.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/2013_ghg_verification_state.pdf
www.youtube.com/watch?v=bt6-gygNcaw
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/012822
thunderbird.asu.edu/
www.fec.gov/data/committee/C00320101/
www.fcx.com/sites/fcx/files/documents/policies/Principles_Business_Conduct-english.pdf?d=20211115
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/052421
fcxcompliance.ethicspoint.com
www.fcx.com/sites/fcx/files/documents/suppliers/lototo_policy_spanish.pdf
www.copper.org/
event.on24.com/wcc/r/2879769/FBCC55B89C0B8C6FFD3C1EACC705F14A
www.fcx.com/sites/fcx/files/documents/fast_facts/climax_EnvironSteward_2015.pdf
www.fcx.com/about/corporate-governance
www.fcx.com/freeport-features/021022
s22.q4cdn.com/529358580/files/doc_financials/10-K/10_k2021.pdf
www.fcx.com/covid-info/040720
www.fcx.com/sites/fcx/files/documents/policies/hr_policy_bahasa.pdf
www.fcx.com/sustainability/environment/tailings-docs
www.fcx.com/covid-19/north-america
www.fcx.com/sites/fcx/files/documents/sustainability/2010_ghg_verification_state.pdf
www.fcx.com/freeport-features/011521
www.fcx.com/sites/fcx/files/documents/fast_facts/arizona.pdf
www.fcx.com/freeport-features/062221
www.fcx.com/freeport-features/102720
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/012921
ec.europa.eu/justice/article-29/structure/data-protection-authorities/index_en.htm
www.fcx.com/covid-info/060920
www.fcx.com/freeport-features/112020
www.fcx.com/operations/north-amer
79f2
ica
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/012022
www.fcx.com/freeport-features/120821
www.fcx.com/freeport-features/01162020
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_Fr_2013.pdf
www.fcx.com/freeport-features/022421
www.fcx.com/suppliers/nola
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/200117
www.fcx.com/sites/fcx/files/documents/sustainability/2020-annual-report-on-sustainability_sp.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/03192020
wwww.FreeportInMyCommunity.com
www.fcx.com/sites/fcx/files/documents/sustainability/vol_principle_2009.pdf
www.fcx.com/sites/fcx/files/documents/suppliers/round-stock.pdf
www.fcx.com/sustainability/people/impacts
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_2017.pdf
www.fcx.com/sites/fcx/files/documents/policies/2017_FCX_PAC_Political_Contributions.pdf
www.youtube.com/watch?v=pSFs581Ah1s&list=PL_7BYaXpr2rX0-PxAfENGcYvoQodTtKWG
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/120821
www.fcx.com/freeport-features/070221
www.fcx.com/sites/fcx/files/documents/policies/inclu_divers_pol_espanol.pdf
d2y36twrtb17ty.cloudfront.net/sessions/9803f971-7e53-4303-8645-acbf003decac/e304ca1f-48dd-4184-b044-acbf003decb4-cdfd09a4-5ce5-4b23-8786-acc90173b506.mp4
www.fcx.com/sites/fcx/files/documents/sustainability/FCX_Tailings_Stewardship_Program.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/200617
www.fcx.com/about/board-of-dir
13ec
ectors
www.fcx.com/operations/nor
7b40
th-america
www.fcx.com/sites/fcx/files/documents/sustainability/audits/PTFI_ExternalEnvironmenta%20Audit2017.pdf
www.fcx.com/sites/fcx/files/documents/features/Miami-Olympian-Brady-Ellison.pdf
www.fcx.com/sites/fcx/files/documents/policies/2017_FCX_Political_Contributions.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/2020_OECD-step5_report.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/FCX2020_ESG_Trend_Data.xlsm
www.irs.gov/pub/irs-pdf/fw7.pdf
www.fcx.com/freeport-features/200331
www.fcx.com/freeport-features/012921
seethemoney.az.gov/Reporting/Explore
www.fcx.com/sites/fcx/files/documents/policies/envi_pol_dutch.pdf?d=20220103
www.fcx.com/node/541
www.fcx.com/sites/fcx/files/documents/sustainability/program_response_water_2017.pdf
www.fcx.com/freeport-features/122821
www.fcx.com/about/our-view-on-governance
www.fcx.com/node/551
investors.fcx.com/investors/stock-and-dividend-information/stock-quote/default.aspx
www.fcx.com/sites/fcx/files/documents/sustainability/2019-annual-report-on-sustainability.pdf
www.fcx.com/freeport-features/062821
investors.fcx.com/investors/investor-resources/rss-feeds/default.aspx
www.fcx.com/about/board-of-directors?bmem=Sara Grootwassink Lewis
www.fcx.com/sustainability
www.fcx.com/sites/fcx/files/documents/policies/tailings-policy.pdf?d=20211209
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/062821
d2y36twrtb17ty.cloudfront.net/sessions/24230b1f-db1a-4f42-8226-abc10161d72a/96674c0c-8ece-4aee-9a15-abc10161d733-d9b3c221-07b4-4b60-8f89-abc101658201.mp4
fcx.com/sites/fcx/files/documents/sustainability/StatementonFutureProjectsandRiverineTailings.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/vol_principle_2017.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/assurance_2011.pdf
www.fcx.com/covid-info/081420
www.fcx.com/sites/fcx/files/documents/covid/power_protection/handwashing_flyer.pdf
www.fcx.com/suppliers/peru
fmi.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=3c312605-f79e-45f4-8c6d-aca9014437e2
in
8216
vestors.fcx.com/investors/financial-information/quarterly-earnings-reports/default.aspx
www.fcx.com/node/122
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/011322
www.fcx.com/sites/fcx/files/documents/policies/pbc_peruvian.pdf?d=20211115
www.fcx.com/sites/fcx/files/documents/fast_facts/ClimaxMoly_Brochure_2014.pdf
www.fcx.com/freeport-features/111521
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/042721
www.fcx.com/sustainability/external-assurance
www.fcx.com/suppliers/ebusiness-information
s22.q4cdn.com/529358580/files/doc_financials/annual/AR_2020.pdf
www.elabra.cl/
desertmuseum.org/buffelgrass/
www.fcx.com/sites/fcx/files/documents/policies/2016_FCX_PAC_Political_Contributions.pdf
www.fcx.com/operations/north-america
www.fcx.com/sites/fcx/files/documents/sustainability/audits/matrix_resp_ptfi_q2_2017.pdf
www.fcx.com/sites/fcx/files/documents/suppliers/hdpe_pipe_handling_policy.pdf
www.fcx.com/sites/fcx/files/documents/suppliers/bus_safety_policy.pdf
investors.fcx.com/investors/financial-information/quarterly-earnings-reports/default.
8390
aspx
investors.fcx.com/investors/
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/032521
www.freeportinmycommunity.com
www.fcx.com/sites/fcx/files/documents/sustainability/audits/Executive_Summary_2014.PDF
www.irs.gov/individuals/international-taxpayers/relevant-irs-forms-and-publications-for-international-taxpayers
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/111021
www.fcx.com/freeport-features/05062021
www.fcx.com/about
www.newsweek.com/americas-most-responsible-companies-2022
www.fcx.com/sites/fcx/files/documents/covid/power_protection/wash_your_hands.pdf
fmi.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=af077c4b-875a-4145-82ef-adbf0177340f
www.fcx.com/sites/fcx/files/documents/suppliers/crane-rigging.pdf
batweek.org/wp-content/uploads/2020/10/Kinder_Module-Morenci_formatted.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/081021
fcx365-my.sharepoint.com/personal/htrumble_fmi_com/Documents/Documents/3BLMedia/www.freeportinmycommunity.com
www.fcx.com/freeport-features/021122
www.fcx.com/covid-19/power_of_protection
www.fcx.com/sustainability/people/impact
504a
s
www.fcx.com/node/1511
en.unesco.org/biosphere
fcx.com/sites/fcx/files/documents/sustainability/FCX_ESG_Investor_Presentation_Q4_2021.pdf?d=20211217
fmi.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=1348a0f4-d414-45aa-9684-ad3c010ce200
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_2012.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/060421
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/05212020
www.fcx.com/covid-info/043020
www.fcx.com/freeport-features/210219
www.fcx.com/sites/fcx/files/documents/sustainability/vol_principle_2011.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/082021
event.webcasts.com/starthere.jsp?ei=1260779&tp_key=3aa8684dee&tp_special=8
fmi.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=1c8dc020-bf6e-4f2f-a1e5-abdd014106e3
www.fcx.com/sustainability/news-archive
jobs.fcx.com/
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/03262020
www.fcx.com/freeport-features/091421
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/10222020
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_fr_2011.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/09212021
www.miningfoundationsw.org/page-1847268
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/08132020
www.fcx.com/sites/fcx/files/documents/sustainability/2014_cdp_info_req.pdf
www.fcx.com/sites/fcx/files/documents/policies/anticorruption_policy_bahasa.pdf
www.fcx.com/freeport-features/07092021
www.fcx.com/freeport-features/200601
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/021121
www.fcx.com/freeport-features/033021
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/200203
www.fcx.com/sites/fcx/files/documents/sustainability/2019_OECD-step5_report.pdf 
www.fcx.com/freeport-features/020121
www.IRS.GOV
www.fcx.com/sites/fcx/files/documents/suppliers/surface_blasting_eng.pdf
fcx365.sharepoint.com/Sites/PHX-NAHR/fmbenefits/Life/Pages/Employee-Assistance-Program.aspx
www.forbes.com/sites/vickyvalet/2020/08/24/meet-americas-best-employers-by-state-2020/
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/04092020
www.fcx.com/freeport-features/08132020
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/070221
globalsupplierportal.apps.fmi.com/
www.fcx.com/sites/fcx/files/documents/sustainability/vol_principle_2018.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_2018.pdf
investors.fcx.com/investors/investor-resources/request-information/default.aspx
www.fcx.com/freeport-features/01302020
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/073020
www.fcx.com/about/copper-at-a-glance
www.fcx.com/freeport-features/082721
fmpartners.fmi.com/
www.fcx.com/sites/fcx/files/documents/sustainability/assurance_2013.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/2017_ghg_verification_state.pdf
www.fcx.com/freeport-features/082021
fundacion.atlantic-copper.com/phocadownload/documentos-vinculos-interes/memorias/06Marismasdelodiel_ReservadeLuzyAlma.pdf
www.ethics.state.tx.us/search/cf/SimpleSearch.php
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/020222
freeportinmycommunity.com
www.fcx.com/freeport-features/102821
www.fcx.com/freeport-features/072021
www.fcx.com/sites/fcx/files/documents/corp_gov/comp_comm_charter.pdf?d=20220209
www.fcx.com/freeport-features/03182021
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/210219
www.fcx.com/freeport-features/070621
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/04302020
www.fcx.com/sites/fcx/files/documents/fast_facts/ark_river_reconstruction_climax.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_2008.pdf
www.fcx.com/cautionary-statement-regarding-forward-looking-statements
www.fcx.com/sites/fcx/files/documents/policies/2012_PAC_Contributions.pdf
www.fcx.com/sustainability/people
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/07092021
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/021122
www.fcx.com/sites/fcx/files/documents/policies/supplier_code_spanish.pdf
www.fcx.com/freeport-features/04092020
www.fcx.com/sites/fcx/files/documents/suppliers/shovel_move_policy.pdf
www.fcx.com/sites/fcx/files/documents/policies/2015_pac_contributions.pdf
www.fcx.com/about/board-of-directors?bmem=Frances Fragos Townsend
fmi.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=e70624cd-ceed-4fcc-a9f2-aced00f95f3b
www.fcx.com/sites/fcx/files/documents/sustainability/FCX2020__ESG_Trend_Data.xlsm?d=20211027
www.fcx.com/about/board-advisors
www.fcx.com/sites/fcx/files/documents/policies/supplier_code_finnish.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/audits/HHRA.pdf
www.fcx.com/suppliers/freeport-compliance-exchange
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_2009.pdf
www.fcx.com/freeport-features/11182021
www.fcx.com/sites/fcx/files/documents/operations/TRS-morenci.pdf
www.fcx.com/freeport-features?year=2021
www.fcx.com/sites/fcx/files/documents/sustainability/UK_Modern_Slavery_Act_Statement_2020.pdf
investors.fcx.com/investors/stock-and-dividend-information/dividend-history/default.aspx
www.fcx.com/sites/fcx/files/documents/sustainability/vol_principle_2012.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/uk_modern_slavery_act_statement_2019.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/200106
www.batweek.org
investors.fcx.com/investors/investor-resources/set-email-alerts/default.aspx
www.fcx.com/freeport-features/200117
fcx.com/sustainability/approach
www.fcx.com/covid-info/092920
www.fcx.com/sites/fcx/files/documents/sustainability/assurance-statement-2018.pdf
www.fcx.com/about/cop
24c3
per-at-a-glance
www.coloradomining.org/
www.fcx.com/sites/fcx/files/documents/fast_facts/Mining_Recl_NA_2014.pdf
www.fcx.com/sites/fcx/files/documents/policies/hr_policy_espanol.pdf
www.fcx.com/sites/fcx/files/documents/suppliers/lototo_policy.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/vol_principle_2020.pdf
www.fcx.com/freeport-features/073020
www.fcx.com/node/536
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/12312020
www.fcx.com/sites/fcx/files/documents/suppliers/msha_training_requirements.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/02182021
www.fcx.com/node/581
www.fcx.com/covid-info/082520
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/102320
www.fcx.com/sites/fcx/files/documents/sustainability/riverine.pdf
www.fcx.com/sites/fcx/files/documents/suppliers/Abra_Clausulas_para_Ordenes_de_Servicio.pdf
fcx.com/sites/fcx/files/documents/sustainability/2019-annual-report-on-sustainability.pdf
www.instagram.com/freeportfcx/
www.fcx.com/freeport-features/021721
www.fcx.com/sites/fcx/files/documents/policies/2012_corp_contributions.pdf
www.fcx.com/freeport-features/102320
www.fcx.com/sites/fcx/files/documents/policies/2020-fcx-privacy-shield-pol.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/072021
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/030521
blogs.cdc.gov/niosh-science-blog/2021/01/13/covid-19-fatigue/
www.fcx.com/sites/fcx/files/documents/sustainability/program_response_water_2016.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_span_2010.pdf
investors.fcx.com/investors/financial-information/quarterly-earnings-reports/default.aspx
www.fcx.com/sites/fcx/files/documents/suppliers/PTFI_PSU.PDF
www.fcx.com/about/board-of-dir
24c3
ectors
www.fcx.com/covid-info/070820
www.fcx.com/operations/north-
830d
america
www.fcx.com/covid-info/052720
www.fcx.com/sites/fcx/files/documents/sustainability/FCX2020_ESG_Trend_Data.xlsm?d=20211027
www.fcx.com/sites/fcx/files/documents/about/Copper_Essential_diagram_ICA-Infographic-Essentiality-202004-FINAL-HiRes.pdf
www.iucn.org/
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/081621
www.fcx.com/about/leadersh
950d
ip
www.fcx.com/sites/fcx/files/documents/corp_gov/FCX_Insider_Trading_Policy2020.pdf
www.fcx.com/freeport-features/082720
www.fcx.com/sites/fcx/files/documents/policies/tailings-policy-bahasa.pdf
d2y36twrtb17ty.cloudfront.net/sessions/3ced7205-a113-42d4-9939-ac670174255c/15d7aec2-9faa-435e-a391-ac6701742565-ff562287-0549-4c26-b51d-ac710116b274.mp4
www.fcx.com/sites/fcx/files/documents/sustainability/assurance_2015.pdf
event.on24.com/wcc/r/1465037/120C9284891400D46BC1FA8550ABF816
www.fcx.com/sites/fcx/files/documents/sustainability/vol_principle_2019.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/2012_ghg_verification_state.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/04232020a
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/01302020
www.sembrandosaberes.cl/
www.fcx.com/suppliers/contract-requirements
www.fcx.com/sites/fcx/files/documents/features/Brady-Ellison-Archery-World-Title.pdf
www.fcx.com/sites/fcx/files/documents/policies/2015_corp_contributions.pdf
www.fcx.com/freeport-features/052421
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/200626
jobs.fcx.com/South-America?locale=es_MX%20
www.fcx.com/freeport-features/04232020a
www.fcx.com/sites/fcx/files/documents/sustainability/supporting_data.pdf
www.nghwdf.org/hwds
www.fcx.com/freeport-features/07222021
www.fcx.com/sites/fcx/files/documents/policies/ResponsibleSourcingofMineralsPolicy.pdf
www.fcx.com/about/leaders
3e2a
hip
www.fcx.com/freeport-features/050421
event.on24.com/wcc/r/2161483/3E636CFA7076C0082E86692A10B8899B
www.fcx.com/freeport-features/12022021
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/070621
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/03182021
fcx.com/freeport-features/011322
www.fcx.com/sites/fcx/files/documents/fast_facts/safford.pdf
www.fcx.com/site-map
www.fcx.com/freeport-features/10222020
www.fcx.com/freeport-features/10012021
www.fcx.com/freeport-features/200507
www.oecd.org/
www.fcx.com/freeport-features/020422
www.fcx.com/freeport-features/100620
fmi.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=79c91646-4120-425e-953a-ada401712736
www.pnas.org/content/117/39/24369
bmo.qumucloud.com/view/2021-gmm-freeport-mcmoran
www.fcx.com/sites/fcx/files/documents/sustainability/assurance_2009.pdf
www.fcx.com/freeport-features/05122020
www.fcx.com/operations/indonesia
www.fcx.com/sites/fcx/files/documents/policies/envi_pol_espanol.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/120121
www.fcx.com/sites/fcx/files/documents/corp_gov/audit_comm_charter.pdf?d=20220209
www.fcx.com/covid-info/022920
www.fcx.com/freeport-features/121721
www.fcx.com/sites/fcx/files/documents/policies/envi_pol_bahasa.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/112921
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/021721
www.fcx.com/about/board-advisors
b911

www.fcx.com/about/board-of-directors?bmem=David P. Abney
www.fcx.com/sites/fcx/files/documents/fast_facts/morenci_tailings_dust_mgmt.pdf
www.fcx.com/freeport-features/120121
www.fcx.com/freeport-features/011422
www.sec.gov/cgi-bin/browse-edgar?company=&CIK=0000831259&owner=only&action=getcompany
www.fcx.com/sites/fcx/files/documents/sustainability/vol_principle_2015.pdf
s22.q4cdn.com/529358580/files/doc_financials/10-Q/FCX-Q321-10-Q.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/assurance_2014.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/073021
www.fcx.com/freeport-features/072321
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/11182021
www.fcx.com/sites/fcx/files/documents/sustainability/2018_ghg_verification_state.PDF
www.fcx.com/sites/fcx/files/documents/policies/saf_health_pol.pdf
www.fcx.com/freeport-features/021121
www.fcx.com/freeport-features/09212021
www.fcx.com/about/multimedia-library
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/090320
www.fcx.com/sites/fcx/files/documents/sustainability/PT_Freeport_Economic_Social_Contribution.pdf?d=20211220
publicportal.fmi.com/cerro_verde
view.publitas.com/freeport-mcmoran/2020-climate-report/
civic50.org
www.fcx.com/sites/fcx/files/documents/policies/envi_pol.pdf?d=20211209
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_fr_2008.pdf
www.fcx.com/sites/fcx/files/documents/policies/ResponsibleSourcingofMineralsPolicy-sp.pdf
www.fcx.com/about/board-of-directors?bmem=Marcela E. Donadio
www.fcx.com/careers
www.fcx.com/sites/fcx/files/documents/policies/tailings-policy-espanol.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/2020_PT-FI_Water_Monitor_%20Sum_Sept.pdf
www.fcx.com/sites/fcx/files/documents/suppliers/material_handling_conveyance.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/assurance_2010.pdf
www.fcx.com/sustainability/approach
www.fcx.com/operations
98ae
/north-america
www.fcx.com/sites/fcx/files/documents/suppliers/Service_Order_Terms_and_Conditions.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/2019-climate-report.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/audits/2017ExternalAuditMatrixQ4.pdf
bradyellison.com/
deloitte.wsj.com/cio/2021/01/29/extracting-value-from-a-digital-transformation-freeport-mcmorans-bert-odinet/?mod=Deloitte_cio_nwsrl
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/102720
www.fcx.com/freeport-features/071621
www.fcx.com/sites/fcx/files/documents/sustainability/vol_principle_2014.pdf
www.fcx.com/freeport-features/05212020
www.fcx.com/freeport-features/06192020
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/111521
me.smenet.org/issueFinder.cfm?context=1&submit=1&criteria=1&monthno=&year=
www.fcx.com/sites/fcx/files/documents/suppliers/Politica_de_Seguridad_de_Buses_FCX-16.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/091520
www.fcx.com/sites/fcx/files/documents/corp_gov/corp_respons_comm.pdf?d=20220209
www.fcx.com/sites/fcx/files/documents/fast_facts/morenci.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_fr_2012.pdf
investors.fcx.com/investors/financial-i
1d19
nformation/annual-reports-and-proxy/default.aspx
www.fcx.com/sustainability/people/community_fatalities
www.fcx.com/sites/fcx/files/documents/sustainability/audits/AERA.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/082721
www.fcx.com/sites/fcx/files/documents/suppliers/csm_french.pdf
www.fcx.com/node/591
www.fcx.com/sites/fcx/files/documents/sustainability/2016_ghg_verification_state.pdf
www.fcx.com/freeport-features/100421
www.fcx.com/about/board-of-directors?bmem=Hugh Grant
view.publitas.com/freeport-mcmoran/morenci-overlook-signage-2021/
www.irs.gov/forms-pubs/about-form-w8
www.fcx.com/sites/fcx/files/documents/sustainability/assurance_2017.pdf
worldarchery.sport/news/200304/brady-ellison-beats-jack-williams-all-usa-recurve-mens-final
www.fcx.com/sites/fcx/files/documents/policies/pbc_bahasa.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/091421
www.fcx.com/about/leadership
www.fcx.com/sites/fcx/files/documents/corp_gov/stock_ownership.pdf?d=20220209
www.un.org/sustainabledevelopment/sustainable-development-goals/
www.fcx.com/sites/fcx/files/documents/suppliers/PTFI_Singapore.pdf
www.fs.fed.us/wildflowers/plant-of-the-week/carnegiea_gigantea.shtml
www.fcx.com/sites/fcx/files/documents/policies/hr_policy.pdf
www.fcx.com/sites/fcx/files/documents/suppliers/hdpe_guidelines_spanish.pdf
www.fcx.com/freeport-features/04162020
www.fcx.com/sites/fcx/files/documents/suppliers/surface_blasting_spanish.pdf
www.minexpo.com/
www.fcx.com/sites/fcx/files/documents/suppliers/PTFI_RPH.PDF
www.fcx.com/sites/fcx/files/documents/policies/2013_FCX_PAC_Political_Contributions.pdf
www.fcx.com/sites/fcx/files/documents/policies/supplier_code_dutch.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/2017_cdp_info_req.pdf
www.fcx.com/sites/fcx/files/documents/policies/2013_FCX_Political_Contributions.pdf
view.publitas.com/freeport-mcmoran/2020-annual-report-on-sustainability/
www.fcx.com/privacy-policy
www.fcx.com/freeport-features/09092021
investors.fcx.com/investors/presentations/default.aspx
www.fcx.com/sites/fcx/files/documents/policies/supplier_code_bahasa.pdf
www.fcx.com/about/board-of-directors?bmem=Robert W. Dudley
www.fcx.com/freeport-features/200626
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/071621
twitter.com/FM_FCX
www.fcx.com/sites/fcx/files/documents/policies/envi_pol_bahasa.pdf?d=20211214
www.fcx.com/sites/fcx/files/documents/sustainability/2011_ghg_verification_state.pdf
www.fcx.com/freeport-features/09102020
www.fcx.com/sites/fcx/files/documents/suppliers/cell_phone_guidelines.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/audits/Executive_Summary_2008.PDF
www.fcx.com/freeport-features/080621
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/200205
www.fcx.com/covid-info/012821
fcx.com/sites/fcx/files/documents/sustainability/2019-climate-report.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/030221
www.fcx.com/sites/fcx/files/documents/covid/power_protection/6ft_apart_2pages.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/01142021
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_span_2014.pdf
investors.fcx.com/investors/investor-resources/shareholder-faqs/default.aspx
www.linkedin.com/company/freeport-mcmoran-inc/
www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager02.html
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/011521
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/083121
www.fcx.com/sites/fcx/files/documents/fast_facts/sierrita_tailings_dust_mgmt.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/09092021
www.fcx.com/freeport-features/200610
www.fcx.com/sites/fcx/files/documents/suppliers/hot_work_policy_spanish.pdf
www.fcx.com/sustainability/approach/policies/direct-corporate-contributions
www.irs.gov/pub/irs-pdf/iw8eci.pdf
www.fcx.com/node/546
www.fcx.com/freeport-features/03192020
www.fcx.com/freeport-features/032521
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_2010.pdf
www.fcx.com/sites/fcx/files/documents/policies/envi_pol_dutch.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/020422
www.fcx.com/sites/fcx/files/documents/policies/2020_FCX_Political_Contributions.pdf
www.un.org/sustainabledevelopment/
www.fcx.com/covid-info/061520
www.fcx.com/sites/fcx/files/documents/policies/envi_pol_espanol.pdf?d=20220111
www.fcx.com/sites/fcx/files/documents/sustainability/PT_Freeport_Managing_Impacts_Responsibly_en.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/032621
investors.fcx.com/investors/news-releases/default.aspx
www.fcx.com/sites/fcx/files/documents/suppliers/hazardous_gas_policy.pdf
www.forbes.com/best-large-employers/
www.fcx.com/freeport-features/12312020
www.fcx.com/sites/fcx/files/documents/fast_facts/new-mexico.pdf
copperalliance.org/
www.fcx.com/sites/fcx/files/documents/sustainability/assurance_2016.pdf
www.fcx.com/sites/fcx/files/documents/fast_facts/texas.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_fr_009.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/assurance_2012.pdf
www.fcx.com/freeport-mcmoran-online-privacy-notice
www.fcx.com/sites/fcx/files/documents/policies/inclusion_diversity_policy.pdf
www.irs.gov/Individuals/International-Taxpayers/Relevant-IRS-Forms-and-Publications-for-International-Taxpayers
view.publitas.com/freeport-mcmoran/metal-market-magazine-katleen-quirk-profile-november-december-2021/
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/09172021
dreambuilder.org/
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/020121
www.fcx.com/freeport-features/020821
www.fcx.com/freeport-features/02182021
www.fcx.com/sites/fcx/files/documents/suppliers/hot_work_policy.pdf?d=20211020
www.fcx.com/freeport-features/03122020
www.privacyshield.gov/article?id=ANNEX-I-introduction
www.fcx.com/sites/fcx/files/documents/policies/envi_pol.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/06192020
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/1125021
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/110520
www.fcx.com/sites/fcx/files/documents/policies/supplier_code_policy.pdf
www.fcx.com/freeport-features/020222
www.fcx.com/sites/fcx/files/documents/fast_facts/colorado.pdf
www.fcx.com/sites/fcx/files/documents/features/tyrone-story.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_span_2016.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/vol_principle_2020.pdf 
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/010722
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/072120
www.fcx.com/covid-info/041620
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/112020
www.fcx.com/sites/fcx/files/documents/covid/power_protection/social_distancing_poster.pdf
www.fcx.com/contact
www.fcx.com/sustainability/approach/policies
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/080621
www.fcx.com/sites/fcx/files/documents/suppliers/IPI_Cairns.pdf
s22.q4cdn.com/529358580/files/doc_financials/10-K/10_k2020.pdf
www.fcx.com/o
7ffe
perations/north-america
www.fcx.com/freeport-features/010721
www.fcx.com/sites/fcx/files/documents/policies/com_pol_fr.pdf
www.fcx.com/sites/fcx/files/documents/suppliers/ElectricalSafetyPolicy.pdf
www.pointsoflight.org/the-civic-50/
www.fcx.com/freeport-features/090920
www.fcx.com/freeport-features/012022
www.fcx.com/sites/fcx/files/documents/operations/TRS-ptfi.pdf
www.fcx.com/freeport-features/082521
www.irs.gov/
fcx.com/sites/fcx/files/documents/policies/anticorruption_policy_dutch.pdf
d2y36twrtb17ty.cloudfront.net/sessions/c2ee25f2-9ae6-41a9-9083-acc20151bbd0/044a1d0f-7b5d-4cda-bf88-acc20151bbda-e1d472c1-faa6-49bc-b692-acc201572395.mp4?
www.irs.gov/Individuals/International-Taxpayers/Taxpayer-Identification-Numbers-TIN
www.fcx.com/sites/fcx/files/documents/corp_gov/nomin_corp_gov_com.pdf?d=20220209
www.fcx.com/sites/fcx/files/documents/sustainability/program_response_water_2015.pdf
www.fcx.com/freeport-features/121621
www.fcx.com/sites/fcx/files/documents/sustainability/vol_principle_2010.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/12242020
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/12022021
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/102021
www.fcx.com/sites/fcx/files/documents/policies/2019_FCX_PAC_Political_Contributions.pdf
www.fcx.com/freeport-features/011321
www.fcx.com/sites/fcx/files/documents/suppliers/csm.pdf
www.fcx.com/freeport-features/061621
www.fcx.com/sites/fcx/files/documents/sustainability/2015_ghg_verification_state.pdf
event.on24.com/wcc/r/2393554/FE3D5611E5156E899DD21EBFF46DD3FF
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_2014.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_span_2009.pdf
www.youtube.com/watch?v=6Lirwytcqgg
www.fcx.com/cautionary-statement
www.irs.gov/pub/irs-pdf/p515.pdf
fcx.com/
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/12042020
www.fcx.com/sustainability/people/due-diligence
www.fcx.com/sustainability/coppermark
connect.uclahealth.org/2020/07/07/7-steps-to-reduce-pandemic-fatigue/
www.fcx.com/freeport-features/081921
www.fcx.com/freeport-features/09032020
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_span_2015.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/audits/PTFIExternal_Audit_Report_UpdateJanuary2014.pdf
www.fcx.com/freeport-features/12042020
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_2013.pdf
www.fcx.com/freeport-features/09242020a
fcx.com/sustainability/people/community-investment
www.fcx.com/sites/fcx/files/documents/sustainability/2019-annual-report-on-sustainability_SP.pdf
www.fcx.com/about/board-of-directors?bmem=John J. Stephens
olympics.com/en/video/brady-ellison-i-was-meant-to-shoot-a-bow
www.fcx.com/sites/fcx/files/documents/fast_facts/cochise_bisbee.pdf
www.responsiblemineralsinitiative.org/
www.fcx.com/freeport-features/073021
www.fcx.com/sites/fcx/files/documents/suppliers/blue_stake_policy.pdf
www.fcx.com/sites/fcx/files/documents/suppliers/industrial_railroad_policy.pdf
investors.fcx.com/investors/financial-information/sec-filings/default.aspx
www.fcx.com/sites/fcx/files/documents/suppliers/admin-policy.pdf
www.fcx.com/freeport-features/082321
www.fcx.com/sites/fcx/files/documents/suppliers/csm_finnish.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/081921
www.fcx.com/freeport-features/030521
event.on24.com/wcc/r/3190371/88AD8627DA22DC5A284EC96289AA7F38
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_2011.pdf
www.fcx.com/freeport-features/06252021
en.unesco.org/biosphere/eu-na/marismas-odiel
www.fcx.com/sites/fcx/files/documents/policies/pbc_dutch.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/wtsd_2015.pdf
www.fcx.com/about/board-of-directors?bmem=Dustan E. McCoy
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/072321
service.ariba.com/Supplier.aw/
www.fcx.com/sites/fcx/files/documents/policies/anticorruption_policy_dutch.pdf
nma.org/
fcxcompliance.alertline.com
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/122821
www.teamusa.org/usa-archery/athletes/Brady-Ellison
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/10012021
www.fcx.com/covid-info/032220
www.fcx.com/freeport-features/200205
www.fcx.com/about/board-of-directors?bmem=Lydia H. Kennard
worldarchery.sport/
www.wildlifehc.org/
fcx.com/freeport-features/020121
www.fcx.com/sites/fcx/files/documents/sustainability/2020-Climate-Report.pdf?d=20211025
www.fcx.com/covid-19/community_health_services
www.fcx.com/sites/fcx/files/documents/suppliers/flagging_barricading_guideline.pdf
www.fcx.com/about/board-of-directors?bmem=Ryan M. Lance
www.irs.gov/pub/irs-pdf/iw8exp.pdf
d2y36twrtb17ty.cloudfront.net/sessions/551eebb6-696f-4b81-9ac4-ac5d0175837a/a8e11d26-5d09-41b2-955d-ac5d01758388-f7d6c7eb-68c5-4715-ba25-ac5d017bcacb.mp4
www.fcx.com/sites/fcx/files/documents/fast_facts/miami.pdf
www.fcx.com/sites/fcx/files/documents/about/ICA-Infographic-Essentiality-202004-SPANISH-1.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/program_response_water_2014.pdf
www.fcx.com/sites/fcx/files/documents/homepage/STAKEHOLDER-COVID19-2020.pdf
twitter.com/intent/tweet/?text=https://www.fcx.com/freeport-features/040721
www.fcx.com/sites/fcx/files/documents/policies/saf_health_pol_fr.pdf
www.fcx.com/sites/fcx/files/documents/suppliers/property_entry_guidelines.pdf
www.fcx.com/covid-info/070320
www.fcx.com/sites/fcx/files/documents/sustainability/FCX_ESG_Investor_Presentation_Q4_2021.pdf?d=20211217
www.fcx.com/ope
8d8b
rations/north-america
www.fcx.com/sites/fcx/files/documents/corp_gov/amend_restated_certif_Incorporation.pdf
www.fcx.com/sites/fcx/files/documents/sustainability/2019_ghg_verification_state.PDF
www.fcx.com/sites/fcx/files/documents/suppliers/REGULACIONES_OBLIGATORIAS_GENERALES.pdf
www.fcx.com/sites/fcx/files/documents/fast_facts/bagdad.pdf
www.fcx.com/freeport-features/02132020
